### ISSUE TITLE
Commit search by commit SHA deesn't work

### ISSUE THREAD

**Issue by julee** [gitkraken/vscode-gitlens#2290] opened 2022-10-24 06:03 UTC
### Description

1. Gitlens search commits
2. select repository
3. Search by commit SHA
4. input any valid commit SHA
5. No result got.

I known old versions work.

### GitLens Version

13.0.3

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.35.1.windows.2

### Logs, Screenshots, Screen Captures, etc

[2022-10-24 05:57:54.903] [GIT  ] [d:/Documents/code/Insta360Code/bmgandroid/bmg] git show -s --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cn%x3e%x20%cN%n%x3cm%x3e%x20%cE%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --use-mailmap a996f27c0 -M -- • Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false show -s --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cn%x3e%x20%cN%n%x3cm%x3e%x20%cE%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --use-mailmap a996f27c0 -M -- • options '--name-only', '--name-status', '--check', and '-s' cannot be used together • 72 ms

**Comment by weijian2014** [comment] 2022-10-27 02:08
I had the same issue, if remove `-s`, it works. e.g. `git show --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cn%x3e%x20%cN%n%x3cm%x3e%x20%cE%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --use-mailmap a996f27c0`
I have rollback to version v12.2.2, it works as well.:)

**Comment by d13** [comment] 2022-10-27 02:45
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2276

This is fixed, pending a patch release.

**Closed by d13** 2022-10-27 02:45 UTC
Labels: duplicate
