### ISSUE TITLE
Have you considered adding multi-language support?

### ISSUE THREAD

**Issue by eachann1024** [gitkraken/vscode-gitlens#2808] opened 2023-07-13 02:07 UTC
Unlike other applications, gitleb has fewer features and does not require a localized language to use it. 

---

So I was wondering if the `gitlens` team has considered adding native language support?

**Comment by jkelroy** [comment] 2024-03-26 01:04
Duplicate of #577

**Closed by jkelroy** 2024-03-26 01:04 UTC
Labels: feature, duplicate
