### ISSUE TITLE
fsPath error when Line History tries to access renamed file

### ISSUE THREAD

**Issue by phoenixeliot** [gitkraken/vscode-gitlens#1944] opened 2022-04-04 16:32 UTC
Issue Type: <b>Bug</b>

I frequently get error bubbles that just say "Cannot read properties of undefined (reading 'fsPath')", with no extra information about which extension it is, stack trace, etc. 

I'm not sure exactly what does this, but it's often (but definitely not consistently) triggered when I open a diff view in the normal git tools or am changing active editor tabs. Right now the consistent repro I have for myself is:
- Click-drag a mouse selection over a specific few lines of code in one specific file
I don't know what's special about this file. Unfortunately I can't share the file.

<img width="480" alt="Screen Shot 2022-04-04 at 12 36 30" src="https://user-images.githubusercontent.com/491376/161590809-092453b7-791e-4fe0-9bf2-3bbba20ff8d7.png">

This is the full stack trace, which was a huge pain to hunt down via the dev tools after identifying it as this extension via extension bisect:
```
TypeError: Cannot read properties of undefined (reading 'fsPath')
    at Tt.getRelativePath (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/env/node/git/localGitProvider.ts:687:56)
    at Tt.getAbsoluteUri (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/env/node/git/localGitProvider.ts:629:29)
    at Object.getAbsoluteUri (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/git/gitProviderService.ts:882:19)
    at Function.fromFile (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/git/gitUri.ts:228:15)
    at new FileRevisionAsCommitNode (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/views/nodes/fileRevisionAsCommitNode.ts:37:9)
    at /Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/views/nodes/lineHistoryNode.ts:142:10
    at filterMap (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/system/iterable.ts:90:18)
    at g.next (<anonymous>)
    at insertDateMarkers (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/views/nodes/helpers.ts:28:13)
    at pr.next (<anonymous>)
    at T.getChildren (/Users/phoenix/.vscode/extensions/eamodio.gitlens-12.0.5/dist/webpack:/gitlens/src/views/nodes/lineHistoryNode.ts:138:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _.fetchChildrenNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19359)
    at _.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:15758)
```
    
In addition to the main topic of this issue, it would be really great if this kind of error reported enough information to hunt it down; hunting this down completely took 40min. The name of the extension and/or a stack trace would be great.

Extension version: 12.0.5
VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 18db7754-a899-47ab-9295-2cc481e3630e|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by phoenixeliot** [comment] 2022-04-04 16:50
A hint, though it means I can't attach logs: When I closed the tab, then relaunched VS Code, then reopened the tab, this went away. Previously when I had a problem like that with Wallaby, it was because the way the editor tracks files. (it has 3 copies of each path in an object, for some reason, and only some update when you rename a file. But I didn't rename this file this time)

I'll try to upload a debug log next this happens.

**Comment by phoenixeliot** [comment] 2022-04-04 16:55
Nvm, that was fast. Here's a debug log, with slightly anonymized file paths. I got this by hitting cmd-A in another file.
<details>
<summary>
Debug logs
</summary>

```
[2022-04-04 16:51:28.801] [  b00] LineAnnotationController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=undefined, pending=true, reason=selection
[2022-04-04 16:51:28.801] [  b01] LineAnnotationController.clear completed • 0 ms
[2022-04-04 16:51:28.801] [  b00] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:28.801] [  b02] LineHoverController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=undefined, pending=true, reason=selection
[2022-04-04 16:51:28.801] [  b02] LineHoverController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:28.801] [  b03] StatusBarController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=undefined, pending=true, reason=selection
[2022-04-04 16:51:28.801] [  b03] StatusBarController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:29.052] [  b05] GitProviderService.getBlameForLine — s=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), e=188, t={"uri":{"$mid":1,"fsPath":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","external":"git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?%7B%22path%22%3A%22%2FUsers%2Fphoenix%2FCode%2Fwork%2FWORK_PROJECT_DIR%2Ffrontend%2Fpages%2Fdevnet%2Floans.page.tsx%22%2C%22ref%22%3A%22%22%7D","path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","scheme":"git","query":"{\"path\":\"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx\",\"ref\":\"\"}"},"fileName":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","isUntitled":false,"languageId":"typescriptreact","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":189}
[2022-04-04 16:51:29.053] [  b06] LocalGitProvider.getBlameForLine — e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), t=188, i={"uri":{"$mid":1,"fsPath":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","external":"git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?%7B%22path%22%3A%22%2FUsers%2Fphoenix%2FCode%2Fwork%2FWORK_PROJECT_DIR%2Ffrontend%2Fpages%2Fdevnet%2Floans.page.tsx%22%2C%22ref%22%3A%22%22%7D","path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","scheme":"git","query":"{\"path\":\"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx\",\"ref\":\"\"}"},"fileName":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","isUntitled":false,"languageId":"typescriptreact","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":189}, o=undefined
[2022-04-04 16:51:29.053] [  b07] LocalGitProvider.getBlame — e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:)
[2022-04-04 16:51:29.053] [  b07] LocalGitProvider.getBlame Cache hit: 'blame:0000000000000000000000000000000000000000:'
[2022-04-04 16:51:29.053] [  b07] LocalGitProvider.getBlame completed • 0 ms
[2022-04-04 16:51:29.053] [  b06] LocalGitProvider.getBlameForLine completed • 0 ms
[2022-04-04 16:51:29.053] [  b05] GitProviderService.getBlameForLine completed • 0 ms
[2022-04-04 16:51:29.053] [  b04] GitLineTracker.updateState returned true • 0 ms — e=188, t=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}
[2022-04-04 16:51:29.053] [  b08] LineAnnotationController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=[0-188], pending=false, reason=selection
[2022-04-04 16:51:29.053] [  b09] LineAnnotationController.refresh
[2022-04-04 16:51:29.053] [  b08] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:29.053] [  b0a] LineHoverController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=[0-188], pending=false, reason=selection
[2022-04-04 16:51:29.053] [  b0a] LineHoverController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:29.053] [  b0b] StatusBarController.onActiveLinesChanged — e=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=[0-188], pending=false, reason=selection
[2022-04-04 16:51:29.053] [  b0b] StatusBarController.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:29.053] [  b09] LineAnnotationController.refresh Line 188 returned no commit
[2022-04-04 16:51:29.053] [  b09] LineAnnotationController.refresh completed • selection(s)=[0-188] • 0 ms
[2022-04-04 16:51:29.304] [  b0c] LineHistoryTrackerNode.onActiveLinesChanged — c=editor=git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}, selections=[0-188], pending=false, reason=selection
[2022-04-04 16:51:29.304] [  b0d] LineHistoryTrackerNode.triggerChange
[2022-04-04 16:51:29.304] [  b0e] LineHistoryTrackerNode.triggerChange — false, false
[2022-04-04 16:51:29.304] [  b0f] LineHistoryView.refreshNode — A=LineHistoryTrackerNode, k=false, ie=false
[2022-04-04 16:51:29.304] [  b10] LineHistoryTrackerNode.refresh — false
[2022-04-04 16:51:29.304] [  b11] GitUri.fromUri — Y=Uri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""})
[2022-04-04 16:51:29.305] [  b12] GitProviderService.getOrOpenRepository — s=Uri(file:///Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx)
[2022-04-04 16:51:29.305] [  b13] GitProviderService.getRepository — s=Uri(file:///Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx)
[2022-04-04 16:51:29.305] [  b13] GitProviderService.getRepository returned /Users/phoenix/Code/work/WORK_PROJECT_DIR • 0 ms
[2022-04-04 16:51:29.305] [  b0c] LineHistoryTrackerNode.onActiveLinesChanged completed • 0 ms
[2022-04-04 16:51:29.305] [  b12] GitProviderService.getOrOpenRepository returned /Users/phoenix/Code/work/WORK_PROJECT_DIR • 0 ms
[2022-04-04 16:51:29.305] [  b11] GitUri.fromUri returned GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:) • 0 ms
[2022-04-04 16:51:29.305] [  b14] LineHistoryTrackerNode.resetChild
[2022-04-04 16:51:29.305] [  b15] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[100,55-100,55])).dispose
[2022-04-04 16:51:29.305] [  b16] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[100,55-100,55])).unsubscribe
[2022-04-04 16:51:29.305] [  b15] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[100,55-100,55])).dispose completed • 0 ms
[2022-04-04 16:51:29.305] [  b14] LineHistoryTrackerNode.resetChild completed • 0 ms
[2022-04-04 16:51:29.305] [  b10] LineHistoryTrackerNode.refresh returned false, uri=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:) • 1 ms
[2022-04-04 16:51:29.305] [  b16] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[100,55-100,55])).unsubscribe completed • 0 ms
[2022-04-04 16:51:29.306] [  b17] LineHistoryView.triggerNodeChange — A=LineHistoryTrackerNode
[2022-04-04 16:51:29.306] [  b17] LineHistoryView.triggerNodeChange completed • 0 ms
[2022-04-04 16:51:29.306] [  b0f] LineHistoryView.refreshNode completed • 1 ms
[2022-04-04 16:51:29.306] [  b0e] LineHistoryTrackerNode.triggerChange completed • 1 ms
[2022-04-04 16:51:29.306] [  b0d] LineHistoryTrackerNode.triggerChange completed • 1 ms
[2022-04-04 16:51:29.311] [  b18] LineHistoryTrackerNode.ensureSubscription
[2022-04-04 16:51:29.311] [  b19] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[0,0-188,0])).ensureSubscription
[2022-04-04 16:51:29.311] [  b1a] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[0,0-188,0])).subscribe
[2022-04-04 16:51:29.311] [  b1b] GitProviderService.getRepository — s=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:)
[2022-04-04 16:51:29.311] [  b1b] GitProviderService.getRepository returned /Users/phoenix/Code/work/WORK_PROJECT_DIR • 0 ms
[2022-04-04 16:51:29.312] [  b1a] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[0,0-188,0])).subscribe completed • 0 ms
[2022-04-04 16:51:29.312] [  b1c] GitProviderService.getLogForFile — s=/Users/phoenix/Code/work/WORK_PROJECT_DIR, e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), t={"all":false,"limit":40,"range":{"start":{"line":0,"character":0},"end":{"line":188,"character":0},"active":{"line":188,"character":0},"anchor":{"line":0,"character":0}},"ref":"0000000000000000000000000000000000000000:","renames":false}
[2022-04-04 16:51:29.312] [  b1d] LocalGitProvider.getLogForFile — e=/Users/phoenix/Code/work/WORK_PROJECT_DIR, t=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), i={"all":false,"limit":40,"range":{"start":{"line":0,"character":0},"end":{"line":188,"character":0},"active":{"line":188,"character":0},"anchor":{"line":0,"character":0}},"ref":"0000000000000000000000000000000000000000:","renames":false}
[2022-04-04 16:51:29.312] [  b1e] GitProviderService.getBlameForRange — s=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), e={"start":{"line":0,"character":0},"end":{"line":188,"character":0},"active":{"line":188,"character":0},"anchor":{"line":0,"character":0}}
[2022-04-04 16:51:29.312] [  b1f] LocalGitProvider.getBlameForRange — e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), t={"start":{"line":0,"character":0},"end":{"line":188,"character":0},"active":{"line":188,"character":0},"anchor":{"line":0,"character":0}}
[2022-04-04 16:51:29.312] [  b20] LocalGitProvider.getBlame — e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:)
[2022-04-04 16:51:29.312] [  b18] LineHistoryTrackerNode.ensureSubscription completed • 0 ms
[2022-04-04 16:51:29.312] [  b19] LineHistoryNode(gitlens:repository(/Users/phoenix/Code/work/WORK_PROJECT_DIR):history:line(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""}[0,0-188,0])).ensureSubscription completed • 0 ms
[2022-04-04 16:51:29.312] [  b21] LocalGitProvider.isTrackedPrivate — e=frontend/pages/devnet/loans.page.tsx, t=/Users/phoenix/Code/work/WORK_PROJECT_DIR, i=0000000000000000000000000000000000000000:
[2022-04-04 16:51:29.312] [  b22] GitProviderService.getRepository — s=Uri(file:///frontend/pages/devnet/loans.page.tsx)
[2022-04-04 16:51:29.312] [  b22] GitProviderService.getRepository returned undefined • 0 ms
[2022-04-04 16:51:29.313] [  b20] LocalGitProvider.getBlame Cache hit: 'blame:0000000000000000000000000000000000000000:'
[2022-04-04 16:51:29.313] [  b21] LocalGitProvider.isTrackedPrivate returned true • 0 ms
[2022-04-04 16:51:29.313] [  b20] LocalGitProvider.getBlame completed • 0 ms
[2022-04-04 16:51:29.314] [  b23] LocalGitProvider.getBlameRange — <blame>, t=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:), i={"start":{"line":0,"character":0},"end":{"line":188,"character":0},"active":{"line":188,"character":0},"anchor":{"line":0,"character":0}}
[2022-04-04 16:51:29.314] [  b23] LocalGitProvider.getBlameRange completed • 0 ms
[2022-04-04 16:51:29.314] [  b1f] LocalGitProvider.getBlameForRange completed • 1 ms
[2022-04-04 16:51:29.314] [  b1e] GitProviderService.getBlameForRange completed • 1 ms
[2022-04-04 16:51:29.342] [GIT  ] [/Users/phoenix/Code/work/WORK_PROJECT_DIR] git log --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cn%x3e%x20%cN%n%x3cm%x3e%x20%cE%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -n41 -m -L 1,189:frontend/pages/devnet/loans.page.tsx • 29 ms
[2022-04-04 16:51:29.342] [  b24] LocalGitProvider.getCurrentUser — e=/Users/phoenix/Code/work/WORK_PROJECT_DIR
[2022-04-04 16:51:29.342] [  b24] LocalGitProvider.getCurrentUser completed • 0 ms
[2022-04-04 16:51:29.342] [  b25] GitLogParser.parse
[2022-04-04 16:51:29.344] [  b25] GitLogParser.parse completed • 1 ms
[2022-04-04 16:51:29.344] [  b1d] LocalGitProvider.getLogForFile completed • 32 ms
[2022-04-04 16:51:29.344] [  b1c] GitProviderService.getLogForFile completed • 32 ms
[2022-04-04 16:51:29.344] [  b26] GitProviderService.getStatusForFile — s=/Users/phoenix/Code/work/WORK_PROJECT_DIR, e=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:)
[2022-04-04 16:51:29.344] [  b27] LocalGitProvider.getStatusForFile — e=/Users/phoenix/Code/work/WORK_PROJECT_DIR, t=GitUri(git:/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx?{"path":"/Users/phoenix/Code/work/WORK_PROJECT_DIR/frontend/pages/devnet/loans.page.tsx","ref":""} repoPath=/Users/phoenix/Code/work/WORK_PROJECT_DIR sha=0000000000000000000000000000000000000000:)
[2022-04-04 16:51:29.352] [GIT  ] [/Users/phoenix/Code/work/WORK_PROJECT_DIR] git status --porcelain=v2 --find-renames -- frontend/pages/devnet/loans.page.tsx • 7 ms
[2022-04-04 16:51:29.352] [  b29] GitStatusParser.parseV2 completed • 0 ms
[2022-04-04 16:51:29.352] [  b28] GitStatusParser.parse completed • 0 ms
[2022-04-04 16:51:29.352] [  b27] LocalGitProvider.getStatusForFile completed • 7 ms
[2022-04-04 16:51:29.352] [  b26] GitProviderService.getStatusForFile completed • 7 ms
[2022-04-04 16:51:29.352] [  b2a] GitProviderService.getCurrentUser — s=/Users/phoenix/Code/work/WORK_PROJECT_DIR
[2022-04-04 16:51:29.352] [  b2b] LocalGitProvider.getCurrentUser — e=/Users/phoenix/Code/work/WORK_PROJECT_DIR
[2022-04-04 16:51:29.352] [  b2b] LocalGitProvider.getCurrentUser completed • 0 ms
[2022-04-04 16:51:29.352] [  b2a] GitProviderService.getCurrentUser completed • 0 ms

```
</details>

**Comment by phoenixeliot** [comment] 2022-04-04 16:57
That one is, as with the other, triggering when I select a pretty specific range of lines. I don't see anything special about the blame for those lines, or anything like that.

**Comment by phoenixeliot** [comment] 2022-04-04 16:59
Aha, here is a great hint: This happens when I even put my cursor on a particular line, and that line has no Line History in the line history panel. This error doesn't happen if I have the line history panel closed.

**Comment by tjx666** [comment] 2022-04-08 09:52
Same here

**Comment by eamodio** [comment] 2022-04-12 22:43
I can't for the life of me reproduce this. Does this still happen in 12.0.6? Are you all on macOS or Linux? (I'm testing on Windows)

**Comment by cmario92** [comment] 2022-04-14 07:45
I am Windows using GitLens 12.0.6

**Comment by eamodio** [comment] 2022-04-14 14:38
@cmario92 can you provide details on how you reproduce this?

**Comment by eamodio** [comment] 2022-05-25 06:38
Can anyone still reproduce this in the just released 12.0.7?

**Comment by tjx666** [comment] 2022-08-03 03:16
Still exists in v2022.8.205

**Comment by eamodio** [comment] 2022-08-03 04:40
I desperately need a reproducible case with a repo -- I know this is happening but I can't reproduce it and I can't tell how it could possibly happen through code inspection.

Does anyone have a repo (that I can access) that reproduces this?

**Comment by Gedrean** [comment] 2022-08-06 00:17
@eamodio sadly cannot provide a full repo but can provide #1896 I've put a comment in with some in-depth points of where it seems to be malforming file URIs to get a bad file path, thus fsPath fails (obviously).

I still don't know why it's coming back as undefined.

I've been trying to build the thing to debug but I'm running into problem after problem because it's hard in Windows lol.

However, it SEEMS possibly that in my case at least since I'm getting a cache hit message, that I think the problem MIGHT be in the nested getBlame calls for the document.state ?  Or further down than that, I can't tell it's very hard to track wtihout being able to run it and debug live...

**Comment by eamodio** [comment] 2022-08-07 04:43
Duplicate of #1896 (which has finally been fixed!)

**Closed by eamodio** 2022-08-07 04:43 UTC
