### ISSUE TITLE
I have to roll back GitLens to version 11.7.0 to uninstall this ext.

### ISSUE THREAD

**Issue by rise-worlds** [gitkraken/vscode-gitlens#1879] opened 2022-03-03 01:54 UTC
fuck `GitKraken Authentication` in GitLens !

**Comment by eamodio** [comment] 2022-03-03 07:11
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1853

**Closed by eamodio** 2022-03-03 07:11 UTC
Labels: feature, triage

**Comment by rise-worlds** [comment] 2022-03-03 07:15
I think you're doing the dirty work. You thought GitKraken was beautiful.

**Comment by eamodio** [comment] 2022-03-03 07:29
Not sure I understand. What do you mean?
