### ISSUE TITLE
[FEATURE] add a setting to specify the gravatar service url

### ISSUE THREAD

**Issue by futuretech6** [gitkraken/vscode-gitlens#2674] opened 2023-05-12 11:34 UTC
gravatar.com is banned in mainland china, but there are some mirror sites of it following the same format (i.e., `https://mirror-site.com/avatar/xxx?s=yyy&d=zzz`)

so if gitlens can support specifying the url to a gravatar service, it might be handy for using gravatar without proxy

**Comment by jkelroy** [comment] 2024-03-26 00:56
Duplicate of #1036

**Closed by jkelroy** 2024-03-26 00:56 UTC
Labels: feature, duplicate
