### ISSUE TITLE
autolinks not detected in commit detail view

### ISSUE THREAD

**Issue by ziofat** [gitkraken/vscode-gitlens#2218] opened 2022-09-19 04:43 UTC
### Description

I have config like this:

```json
  "gitlens.autolinks": [
        {
            "prefix": "!",
            "url": "https://git.my-company.com/project/merge_requests/<num>",
            "title": "Merge Request !<num>"
        },
        {
            "prefix": "#",
            "url": "https://git.my-company.com/project/issues/<num>",
            "title": "Issue #<num>"
        },
    ]
```

And the links can be detected in hover view:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/8521174/190950942-e28bab0b-c647-426f-aaa4-24d3061051a6.png">

But not in commit detail view:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8521174/190950986-3b42a3e7-8c90-4df0-ac0a-8323f2fe3deb.png">

### GitLens Version

12.2.2

### VS Code Version

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

### Git Version

git version 2.24.3 (Apple Git-128)

**Comment by eamodio** [comment] 2022-10-03 03:03
Duplicate of #2203

**Closed by eamodio** 2022-10-03 03:03 UTC
Labels: feature, area-autolinks
