### ISSUE TITLE
No remote providers found: help link is useless

### ISSUE THREAD

**Issue by DanaGoyette** [gitkraken/vscode-gitlens#2763] opened 2023-06-22 16:46 UTC
### Description

I just installed the GitLens addon, and when I try to use `Open on Remote (Web)`, it opens a dialog stating: `No auto-detected or configured remote providers found`

My remotes are on employer-hosted on-site Gitlab repos in this form, with TLD, group, and repo name redacted:
`git@code.corp.mydomain.com:mygroup/myproject.git`

The problem is that the `See how to configure a custom remote provider...` link takes me to an anchor that doesn't exist in the documentation:
https://github.com/gitkraken/vscode-gitlens#remote-provider-integration-settings-

### GitLens Version

14.0.1

### VS Code Version

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z (1 wk ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Git Version

git version 2.41.0

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/1697486/1e70f05b-8615-4ba1-8e80-5d39e05038ac)

**Comment by d13** [comment] 2023-06-22 18:01
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2760

**Closed by d13** 2023-06-22 18:01 UTC
Labels: bug, triage, duplicate
