### ISSUE TITLE
File History in Source Control Tab

### ISSUE THREAD

**Issue by DKhalil** [gitkraken/vscode-gitlens#2754] opened 2023-06-19 13:17 UTC
Hello!

While I really enjoy the depth of the file history possible now in the Inspect tab, I mostly use the source control tab for navigating the repo and I really do miss having a general overview of the file history there. Is it possible to re-enable it there? It would be greatly appreciated.

**Comment by jkelroy** [comment] 2023-06-19 17:26
Duplicate of #2753

**Closed** 2023-06-19 17:27 UTC
Labels: already-exists
