### ISSUE TITLE
Filter menu is cut off

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [gitkraken/vscode-gitlens#1553] opened 2021-06-23 06:44 UTC
Issue Type: <b>Bug</b>

The file filter option in search and compare is behind the editor.

![image](https://user-images.githubusercontent.com/86342787/123048811-19542c00-d3ff-11eb-9a67-3d77ee7d31e7.png)

Extension version: 11.5.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.16GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30323119

```

</details>

**Comment by eamodio** [comment] 2021-06-28 04:07
This is caused by this bug in VS Code: https://github.com/microsoft/vscode/issues/110083

**Comment by eamodio** [comment] 2023-10-21 16:27
It looks like this has been resolved in VS Code

**Closed by eamodio** 2023-10-21 16:27 UTC
Labels: bug, blocked: vscode, blocked
