### ISSUE TITLE
Creating/Deleting Branch failed to quote path

### ISSUE THREAD

**Issue by diana-cn** [gitkraken/vscode-gitlens#2275] opened 2022-10-18 20:36 UTC
### Description

If my understanding is correct there are two ways to create/delete a branch in VS Code with GitLens installed: 

1. Ctrl+Shift+P and use the built-in command palette from VS Code.
2. In the Source Control - Branches view, right click on a branch and select "Create Branch...", or use the + sign in this view. 

When I use the second method, which I assume is from GitLens, to create a branch, VS Code opens up a terminal with the error:

```
git -C [my repo path which has hyphens and spaces] branch test main
unknown option: -
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]
```

The problem is that my repo path has hyphens and spaces, but is unquoted, thus git seems to recognise it as me trying to give an option to it, the same happens when I try to delete a branch. This behaviour is consistent in the recent v13.0.x versions. I then rolled back to the previous version v12.2.2 and tested the exact same steps, the terminal shows that the command executed was divided into two steps, one `cd` with my quoted path and one `git branch test main`, which works fine. 

### GitLens Version

13.0.2

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 6.3.9600
Sandboxed: No

### Git Version

git version 2.33.0.windows.1

**Comment by DBojsen** [comment] 2022-10-18 21:20
Have exactly same issue on Mac.  
VS Code Insiders version: 1.73.0-insider (Universal)
GitLens version: 13.0.2

**Comment by eamodio** [comment] 2022-10-19 03:05
Duplicate of #2271

**Closed by eamodio** 2022-10-19 03:05 UTC
Labels: potential-bug, triage
