### ISSUE TITLE
Remove the persistent notification that says "Sign in with GitHub to use GitLens"

### ISSUE THREAD

**Issue by aydwi** [gitkraken/vscode-gitlens#1759] opened 2022-01-03 14:47 UTC
<img width="416" alt="image" src="https://user-images.githubusercontent.com/29029116/147943246-4334e835-3f91-4cba-8609-115db5efd79f.png"> <img width="42" alt="image" src="https://user-images.githubusercontent.com/29029116/147943765-ce7b4afd-2e4f-436d-971a-e09329f34c31.png">

As of late, GitLens has started showing a persistent notification bubble on VS Code asking you to "Sign in with GitHub to use GitLens".

1. Why do I need to sign in with GitHub? What does that achieve?
2. Why use misleading language? The extension continues to work without signing in with GitHub, so why say "Sign in to use..."?
3. Why make it a persistent notification?

Please provide some documentation on what this is and why this is required. If possible, add a feature to dismiss this banner/notification.

```
GitLens version: v11.7.0
VS Code version: 1.63

```

**Comment by eamodio** [comment] 2022-01-03 17:54
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1506

**Closed by eamodio** 2022-01-03 17:54 UTC
Labels: bug, duplicate
