### ISSUE TITLE
Cherry pick fails when git worktree path contains a space

### ISSUE THREAD

**Issue by bluemonkmn** [gitkraken/vscode-gitlens#2273] opened 2022-10-18 15:21 UTC
### Description

1. Working in a (non-primary) worktree located in C:\users\bmarty\Non-Synced Files\Code\hcm
2. Running VS Code in this directory, I execute GetLens: Git Cherry Pick
3. I pick a change I made on another branch and choose the option to cherry pick without commit
4. An error appears in the GitLens console output: Directory C:\users\bmarty\Non-Synced Not Found

### GitLens Version

13.0.2

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

git version 2.37.3.windows.1

**Comment by eamodio** [comment] 2022-10-19 03:05
Duplicate of #2271

**Closed by eamodio** 2022-10-19 03:05 UTC
Labels: duplicate
