### ISSUE TITLE
Still doesn't work on github.dev

### ISSUE THREAD

**Issue by dzid26** [gitkraken/vscode-gitlens#2957] opened 2023-10-10 17:22 UTC
### Description

Reopening 
https://github.com/gitkraken/vscode-gitlens/issues/2703#issue-1732111114

### GitLens Version

 v14.3.0

### VS Code Version

github.dev 
Windows 21H2
Chrome 117.0.5938.134 (Official Build) (64-bit)

### Logs, Screenshots, Screen Captures, etc

![image](https://github.com/gitkraken/vscode-gitlens/assets/841061/c913c96d-b38e-4e79-921c-ce13f1d4e579)

Login-in also doesn't work:
![image](https://github.com/gitkraken/vscode-gitlens/assets/841061/04962aeb-52f1-4f11-adb7-54c94c512fb4)
![image](https://github.com/gitkraken/vscode-gitlens/assets/841061/51615731-f726-4ea2-965f-42fdc22b461f)

**Comment by axosoft-ramint** [comment] 2023-10-10 18:51
@dzid26 I was able to reproduce it. This seems to be an issue with github.dev.

I've opened an issue here: https://github.com/microsoft/vscode/issues/195286

For the time being, I was able to get around it by doing the following:

1. Hit `Cancel` on the initial auth prompt

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/976710de-12e9-4a35-ada9-09f34e33e209)

2. Grant access from the account sidebar

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/78873b3e-8a46-4f5a-a4e6-c762ec98d899)

3. Hit `Allow` on the new prompt

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/feeeb6da-aeec-4ef7-b69d-15fd3636ed95)

4. Refresh the page

**Comment by d13** [comment] 2023-10-10 18:52
@dzid26 please provide OS and Browser with version. Thanks!

**Comment by axosoft-ramint** [comment] 2023-10-13 18:19
This issue was fixed on github.dev. You can verify today by switching to the Insiders version on github.dev:

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/f4a78dd6-2045-4520-a81a-a6add37f6b11)

**Closed by axosoft-ramint** 2023-10-13 18:19 UTC
Labels: bug, blocked: vscode, blocked
