### ISSUE TITLE
Commit details "Autolinks" group shows wrong count and expands unwantedly

### ISSUE THREAD

**Issue by sebastianzander** [gitkraken/vscode-gitlens#2339] opened 2022-11-11 08:23 UTC
### Description

Since I see that the issue number in commit message be made an clickable link (see attached screenshot), I would expect the collapsible "Autolinks" group to show "1 found".

Additionally the collapsed state of this group also is not saved, so whenever I change the tab in the secondary side bar, first of all I see the "Move into Secondary Side Bar" notice over and over again (see #2338), secondly after closing that notice and changing the displayed commit, the "Autolinks" group is expanded again.

It would be nice if you could permanently hide this group; once I have configured my autolinks I don't really need this group, anymore.

if I have misunderstood this feature, please tell me.

### GitLens Version

13.0.4

### VS Code Version

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.38.1

### Logs, Screenshots, Screen Captures, etc

![gitlens_commit_details](https://user-images.githubusercontent.com/11301464/201296167-5699ad9a-ac5c-4587-aaa6-8bcb8c56642c.jpg)

**Comment by eamodio** [comment] 2022-11-11 18:47
We believe this issue should be resolved in the latest pre-release edition of GitLens. Can you please give it a try to confirm that the issue is resolved for you? Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by sebastianzander** [comment] 2022-11-14 14:55
> You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.
I already installed the pre-release version v2022.11.1404 to test my other issue #2338, which I could close then.

Still, it is still the same as before and as can be seen in the screenshot above. It says "Autolinks 0 found", although there is a clickable link in the first line of the commit. I have seen an older commit where there was an issue number which was not made to a clickable link, however. These issue numbers are in the form `#123456`, so I assume that a prefix of `#` will work, or won't it?

**Comment by d13** [comment] 2022-11-16 06:27
Resolved by b3cf9c38538ad4bf32b72f4fa3e12f2031bf4095

**Closed by d13** 2022-11-16 06:27 UTC
Labels: bug

**Comment by sebastianzander** [comment] 2022-11-17 11:21
Since the "Autolinks" group changed I assume that GitLens updated in the background. It is now on `v2022.11.1704`

However, now it looks like this:
![gitlens_autolinks_incorrect](https://user-images.githubusercontent.com/11301464/202432600-33f2556c-02f7-4504-92a6-bcf63cfef04d.jpg)

I have two prefixes configured as you can see in the screenshot, but for some reason GitLens now generates a clickable link which leads to gitlab.local.hacon.de. This server hosts our git repositories but we don't use GitLab's Issues function. So the generates links lead nowhere.

The clickable link in the first line of the commit message remains correct, after all. Are these links even generated by GitLens?

**Comment by d13** [comment] 2022-11-17 17:20
Great catch! The message and the list are both gathering autolinks from the same sources, I just combined them wrong in the autolinks list. Sorry about that. Resolved with 07cce470cb7d15eb4a5d1b108efcd9221b6fbc61

**Comment by sebastianzander** [comment] 2022-11-18 13:26
> Great catch! The message and the list are both gathering autolinks from the same sources, I just combined them wrong in the autolinks list. Sorry about that. Resolved with [07cce47](https://github.com/gitkraken/vscode-gitlens/commit/07cce470cb7d15eb4a5d1b108efcd9221b6fbc61)

Works fine! 👌  Thank you so much.
