### ISSUE TITLE
Revision Navigation bar disappeared

### ISSUE THREAD

**Issue by natajacks** [gitkraken/vscode-gitlens#2642] opened 2023-04-18 16:33 UTC
### Description

Hi,

I don't see the revision navigation buttons in VS Code that I have seen in the past from GitLens. 

Thank you,

Natalie

### GitLens Version

13.5.0

### VS Code Version

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

### Git Version

git version 2.39.1.windows.1

### Logs, Screenshots, Screen Captures, etc

![image](https://user-images.githubusercontent.com/106553965/232844221-17b67a75-0478-4eb9-97f7-6a9e5e3b57dd.png)

**Comment by eamodio** [comment] 2023-04-27 19:27
@natajacks  Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by natajacks** [comment] 2023-04-27 20:41
Hi @Roberto-Vizcarra I'm not seeing that option in my settings.

@eamodio is this the log you're looking for?

[vs_code_terminal_output_gitlens_debug_logging_enabled.txt](https://github.com/gitkraken/vscode-gitlens/files/11347691/vs_code_terminal_output_gitlens_debug_logging_enabled.txt)

I'm wondering if my problem is related to the network drive settings rather than git/gitlens.

Thank you both for your help.

**Comment by m-shum** [comment] 2023-08-14 21:17
Having this issue out of the blue. Yesterday everything was where it used to be, today it's missing. I did not update VSCode and my revision history commands are enabled in gitlens settings.

**Comment by snax4a** [comment] 2023-08-28 11:27
On my end the navigation buttons are present in the file view, but when I navigate to the previous revision they disappear.
However there is a three-dot button on the right, and it contains these navigation options, looks like there are too many toolbar actions when revision is shown and vscode hides some of the actions under this three-dot button.

Maybe it is somehow possible to choose which options I would like to have visible, but I was not able to find it yet.

**Comment by brunnerh** [comment] 2023-09-29 10:02
Tried to find a setting to increase the maximum of 8 actions, but did not find anything.
With tab wrapping there is more than enough space there.

Disabled a few things via the context menu on the actions to get previous/next back.
![image](https://github.com/gitkraken/vscode-gitlens/assets/834235/810edf3d-b353-4834-afdb-690dcb69cbbc)

**Comment by MylesWardell** [comment] 2024-01-05 05:01
> Tried to find a setting to increase the maximum of 8 actions, but did not find anything. With tab wrapping there is more than enough space there.
> 
> Disabled a few things via the context menu on the actions to get previous/next back. ![image](https://private-user-images.githubusercontent.com/834235/271537167-810edf3d-b353-4834-afdb-690dcb69cbbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzExODUsIm5iZiI6MTcwNDQzMDg4NSwicGF0aCI6Ii84MzQyMzUvMjcxNTM3MTY3LTgxMGVkZjNkLWIzNTMtNDgzNC1hZmRiLTY5MGRjYjY5Y2JiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNTAxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YThiZDE0MjJmNzZhZTAxZTUxOGEzYWVkYmJlYTI3YjViNTJmNDA1OWQ1YjAwZjI2N2U3ODIzOTkyNmU5MGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2zVxpUhhE42-OeMnpnkocBidnuigQ3SW_mhjNbV0Btg)

This was the solution for me. Disable a bunch if features until the important one comes back. So stupid

**Comment by eamodio** [comment] 2024-01-05 05:26
Agreed. Please open an issue with VS Code on this as there isn't anything extensions can do to get around that limit.

**Comment by leopascual** [comment] 2024-02-02 23:00
I have a similar issue. Although mine disappears after hitting the first click, so I can only review last change vs current. 
Last versions are in all extensions. 

![Screenshot 2024-02-02 at 4 57 09 PM](https://github.com/gitkraken/vscode-gitlens/assets/43121349/8abb3cbf-3c65-46a7-9ab4-ec0885571c61)
![Uploading Screenshot 2024-02-02 at 4.57.09 PM.png…]()

**Comment by imYourChoi** [comment] 2024-07-26 04:03
Same for me. I did not update VSCode or anything. It was working totally well until yesterday but it disappeared today.

![image](https://github.com/user-attachments/assets/f921a702-1a0d-4d65-8094-3bfb22ee704c)

![image](https://github.com/user-attachments/assets/37eafe2d-8883-487d-b6a0-98ce476ccfa2)

If i access the diff window through GitLens Inspect in the activity bar, the toolbar then appears.

![image](https://github.com/user-attachments/assets/7434fdb5-6caa-405e-9d20-8c7375bbfd7a)

**Comment by eamodio** [comment] 2024-07-26 04:08
@imYourChoi this should be fixed in tomorrow 's pre-release version and if all looks good tomorrow we'll release a patch for the main version right after.

**Closed** 2024-09-06 17:08 UTC
Labels: bug
