### ISSUE TITLE
Extension loading error in docker container

### ISSUE THREAD

**Issue by schegde** [gitkraken/vscode-gitlens#1839] opened 2022-02-28 19:14 UTC
Seems like with the latest v12 release, I am starting to see this error inside a VSCode instance attached to a docker container :
`Cannot activate the 'GitLens — Git supercharged' extension because it depends on the 'GitKraken Authentication' extension, which is not loaded. Would you like to reload the window to load the extension?`
Of course I tried reloading window multiple times but doesn't seem to help.
![image](https://user-images.githubusercontent.com/25887290/156043633-b8869b47-02a3-47eb-86b0-5ec23b9e17cb.png)

- GitLens Version: v12.0.0
- Git Version: 2.25.1

- VSCode Version: 
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
- OS Version: Linux Ubuntu 18.04

I can confirm this new version of extension works fine inside the Linux native instance of VSCode . I am seeing above issue only inside the official docker Ubuntu image pulled.

**Comment by traviscrawford** [comment] 2022-02-28 19:20
I believe https://github.com/gitkraken/vscode-gitlens/issues/1840 is the same root cause - the `GitKraken Authentication` plugin is installed "locally", while the GitLens plugin is installed in the "remote" environment. GitLens and its dependencies must be installed in the same location (e.g.: both remote, or both local).

**Comment by traviscrawford** [comment] 2022-02-28 19:41
See https://github.com/gitkraken/vscode-gitlens/issues/1840 for details. TL;DR a fix has been merged and a new release is coming shortly.

**Comment by schegde** [comment] 2022-02-28 19:45
> I believe #1840 is the same root cause - the `GitKraken Authentication` plugin is installed "locally", while the GitLens plugin is installed in the "remote" environment. GitLens and its dependencies must be installed in the same location (e.g.: both remote, or both local).
Hahaha, sounds like me and you create the issue posts at pretty much the same time!. Yes understood , I can confirm what you mentioned in the docker container too - GitKraken Authentication is installed locally , and Gitlens inside the container. So I tried to install GitKraken plugin inside the container, but seems like it always gets installed "locally" ; Also looks like reading from that other thread, the fix isnt available on marketplace yet, I will just wait for that, and give it a try once live! Thanks..

**Comment by eamodio** [comment] 2022-02-28 19:54
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1836 which will be fixed in a couple of minutes.

**Closed by eamodio** 2022-02-28 19:54 UTC
Labels: potential-bug, triage
