### ISSUE TITLE
Wrong behavior when pushing a local branch whose name differs from its tracking branch

### ISSUE THREAD

**Issue by sodevel** [gitkraken/vscode-gitlens#3015] opened 2023-11-13 22:46 UTC
### Description

In my local repository i have setup two remotes, `origin` and `upstream`. I have a local branch called `master` that tracks `origin/master` and another local branch called `umaster` that tracks `upstream/master`.

Now, when i use GitLens to push `umaster` (e.g. pressing the Push button next to the commit in the Commits view of the Repository) a new branch `umaster` gets pushed to `upstream` which points to the same commit like `master` (which is much older than `umaster`). Additionally, in the `config` file of my local git repository, the configuration of the local branch `master` gets changed to track `upstream/umaster`.

Well, this is not what should happen. A simple `git push` on the command line works as intended. In the repository configuration i have set `push.default = upstream`, everything else is default, especially i have not set `remote.pushDefault` nor `branch.<name>.pushRemote`.

### GitLens Version

v14.4.1

### VS Code Version

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.36.0.windows.1

**Comment by axosoft-ramint** [comment] 2023-11-13 22:57
@sodevel Can you please see if this issue is still reproducible in the pre-release edition of GitLens? Asking because I think this is related to a known issue that we have already fixed (and the fix should be available in the next release).

You can switch to the pre-release edition of GitLens by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/fd5801ea-a4f6-47aa-9081-910ab7615803)

**Comment by sodevel** [comment] 2023-11-14 17:36
I just tested this with version v14.5.0 which got released today, the issue is fixd, thanks.

**Comment by axosoft-ramint** [comment] 2023-11-14 18:08
Fixed in 14.5.0

**Closed by axosoft-ramint** 2023-11-14 18:08 UTC
Labels: bug, triage
