### ISSUE TITLE
CodeLens blame lines appear even if disabled

### ISSUE THREAD

**Issue by adrfantini** [gitkraken/vscode-gitlens#2234] opened 2022-09-26 14:45 UTC
### Description

I can't seem to be able to disable CodeLens blame lines.
Even if disabled, as in the following screenshot, they still appear.

I tried uninstalling the extension, and they disappeared. Upon reinstall, they appeared again despite being disabled in the User configuration.

If I toggle them off, they disappear, but will reappear at the next VSCode restart.

The only way to definitely turn them off is to open the VSCode extension settings, and manually turn off all settings, since, as showed in the second screenshot, they were still enabled, which is a bit weird since from the settings helper CodeLens was disabled.

### GitLens Version

v12.2.2

### VS Code Version

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

Settings helper:
![Screenshot_20220926_163346-1](https://user-images.githubusercontent.com/12826141/192304797-aaabd046-002c-4db6-92af-1cf9d513aa95.png)

The above setup results in the following extension basic settings:
![Screenshot_20220926_164137-1](https://user-images.githubusercontent.com/12826141/192306486-5fda28bd-4132-4551-b9c1-e78d50fb3035.png)

**Comment by eamodio** [comment] 2022-09-26 17:43
@adrfantini I can't reproduce this. If I uncheck Git CodeLens like in your screenshot I see the CodeLens disappear. Are you using GitLens Modes to enable/disable certain features? Or even with Git CodeLens disabled you can still toggle them on temporarily via the `Toggle Git CodeLens` command -- was that run (though that would go away on a vscode reload)?

Any more details you can provide? What GitLens settings do you have set in your `settings.json`?

**Comment by adrfantini** [comment] 2022-09-27 06:57
> @adrfantini I can't reproduce this. If I uncheck Git CodeLens like in your screenshot I see the CodeLens disappear. Are you using GitLens Modes to enable/disable certain features? Or even with Git CodeLens disabled you can still toggle them on temporarily via the `Toggle Git CodeLens` command -- was that run (though that would go away on a vscode reload)?
> 
> Any more details you can provide? What GitLens settings do you have set in your `settings.json`?

Sure!

- This installation is almost vanilla so I have not messed with the CodeLens settings much. I don't think I'm using Modes.
- I'm able to use the toggle command even with the CodeLens setting disabled in the quick setup helper, since `gitlens.codeLens.authors.enabled` and `gitlens.codeLens.recentChange.enabled` are still `true`.
- If I deactivate `Git CodeLens` in the quick setup helper, `gitlens.codeLens.authors.enabled` and `gitlens.codeLens.recentChange.enabled` remain `true` (they are missing from `settings.json` and I assume `true` is their default behaviour), and CodeLens still works, despite `"gitlens.codeLens.enabled": false` in `settings.json`.
- If I manually force `gitlens.codeLens.authors.enabled` and `gitlens.codeLens.recentChange.enabled` to `false`, either in `settings.json` or from the extension settings, CodeLens correctly disappears.
- I'm NOT able to use the toggle command if I disable CodeLens `gitlens.codeLens.authors.enabled` and `gitlens.codeLens.recentChange.enabled`.

**Comment by d13** [comment] 2023-03-09 21:53
This was resolved with #2549

**Closed by d13** 2023-03-09 21:53 UTC
Labels: potential-bug, triage
