### ISSUE TITLE
page goes up and down when typing a char

### ISSUE THREAD

**Issue by enzodanjour** [gitkraken/vscode-gitlens#1874] opened 2022-03-02 18:08 UTC
- GitLens Version:12.0.0
- Git Version: git version 2.25.1
- 
- VS Code version: Code 1.64.2 (https://github.com/microsoft/vscode/commit/f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
- OS version: Linux x64 5.13.0-30-generic

Steps to Reproduce:

1. press any key 

https://user-images.githubusercontent.com/35856303/156422056-2c9873fa-8807-4970-8829-73f6c5bb3195.mp4

**Comment by eamodio** [comment] 2022-03-02 20:12
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1742

**Closed by eamodio** 2022-03-02 20:12 UTC
Labels: potential-bug, triage
