### ISSUE TITLE
After version 12.2.0, `Source Control` -> `COMMITS` becomes very very slow

### ISSUE THREAD

**Issue by sunshaoce** [gitkraken/vscode-gitlens#2188] opened 2022-09-02 06:39 UTC
### Description

After version 12.2.0, `Source Control` -> `COMMITS` becomes very very slow. Version 12.1.2 can be normally used.

### GitLens Version

12.2.0

### VS Code Version

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

### Git Version

git version 2.37.3.446.gd42b38dfb5

### Logs, Screenshots, Screen Captures, etc

<img width="755" alt="image" src="https://user-images.githubusercontent.com/57467643/188074295-3e212736-7bed-4a30-b7a2-be9793f65951.png">

**Comment by Camo30** [comment] 2022-09-02 07:05
Same issue here. After pressing the "Refresh" button it works but one have to use that button again and again.

**Comment by mmuller2** [comment] 2022-09-02 07:26
Same issue here! tremendously slow to update commits in order to compare.

**Comment by ASMohamedFaheemAnver** [comment] 2022-09-02 09:54
Yah, I am also facing the issue :(

**Comment by ASMohamedFaheemAnver** [comment] 2022-09-02 09:59
For now, I have downgraded the extension version. Check this out [](https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version)

**Comment by ASMohamedFaheemAnver** [comment] 2022-09-02 10:00
For now, I have downgraded the extension version. Check this [link](https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version)

**Comment by jaspreet57** [comment] 2022-09-03 07:27
Same issue here, not only the commits of current branch, but also commits in code comparision and remote branches have slowed down. In mycase it freezes completely, untill I restart vscode.

So downgrading for now to 12.1.2, until this bug fixed.

https://user-images.githubusercontent.com/10244949/188260686-a9e74313-5f04-4947-82da-c9690ccbfcc7.mov

**Comment by eamodio** [comment] 2022-09-05 21:57
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2177

**Closed by eamodio** 2022-09-05 21:57 UTC
Labels: bug, duplicate
