### ISSUE TITLE
Don’t prompt for auth on activation on web

### ISSUE THREAD

**Issue by TylerLeonhardt** [gitkraken/vscode-gitlens#2159] opened 2022-08-23 14:34 UTC
### GitLens Version

12.1.2

### VS Code Version

1.70.0-insiders

### Git Version

N/A in the web

### Description

GitLens currently asks for auth on activation in the web. This leads to users being annoyed:
https://github.com/microsoft/vscode/issues/158911
If they don’t want to login just yet.

My recommendation is for them to not prompt every time GitLens activates (which is every time) and instead only prompt when acted upon by the user:

* when the user clicks on a button in a welcome view
* in-line editor decoration
* on command

### Logs, Screenshots, Screen Captures, etc

https://user-images.githubusercontent.com/1794099/186180805-1db664f8-f5c2-4a65-ad36-37632a43fd02.mov

**Comment by eamodio** [comment] 2022-08-28 01:31
Closing as duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2166 (since I forgot about this issue)

**Closed by eamodio** 2022-08-28 01:31 UTC
Labels: potential-bug, triage
