### ISSUE TITLE
Add rich integration for Github Enterprise

### ISSUE THREAD

**Issue by jasonwilliams** [gitkraken/vscode-gitlens#1210] opened 2020-11-25 12:59 UTC
I've tried setting up a remote to an Enterprise Server using `"gitlens.remotes": [{ "domain": "git.corporate-url.com", "type": "GitHub", "protocol": "https" }]` but this triggers an authentification workflow that takes me to github.com. Even though I authenticate correctly there it's the wrong Github so it this doesn't work. (also is there a way to reset this?)

Can i have an option to pass in a token instead from my Enterprise Github account?

I can't seem to avoid the "The extension 'GitLens — Git supercharged' wants to sign in using GitHub."

Github Pull Request extension allows the user to do this:
https://github.com/microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication

Now i just get:
```
[2020-11-25 13:00:15:177] GitHubApi.getPullRequestForCommit
Error: Bad credentials
```

in my logs when i run commands that need the server.

**Comment by jasonwilliams** [comment] 2020-12-07 17:19
> I believe so -- during the VS Code auth flow (when it opens the browser window), I believe there is an entry in the statusbar that you can click that will prompt for a PAT. But I don't believe you can create a PAT with any less scopes than I am currently asking for -- because repo info, prs, issues etc are all under the repo scope.

Weird i tried creating a token with `repo` scope and it failed for me:
```
[Info  - 17:11:35.813] Logging in...
[Info  - 17:12:44.990] Treating input as token
[Info  - 17:12:44.990] Getting user info...
[Error  - 17:12:45.321] Getting account info failed: Unauthorized
```

**Comment by eamodio** [comment] 2020-12-07 19:35
Unfortunately this is an issue with the VS Code auth provider: https://github.com/microsoft/vscode/issues/112043 

Until this is resolved, this unfortunately will be blocked (as I don't want to get into managing/storing secrets myself).

**Comment by jasonwilliams** [comment] 2020-12-07 19:40
no problem, thanks for raising @eamodio @RMacfarlane !

**Comment by jasonwilliams** [comment] 2021-05-07 22:45
Hey @eamodio https://github.com/microsoft/vscode/issues/112043 has now been fixed and merged!

**Comment by kglickman** [comment] 2021-11-29 15:20
This feature has been working fine for me for months and suddenly stopped working.  I think something may have gotten broken in VSCode version 1.62.3, though I haven't proven it yet.  @eamodio Do you know anything about this?

**Comment by kglickman** [comment] 2021-11-29 15:29
Yes, I have confirmed that it broke in 1.62.3.  I've downgraded to 1.62.2 and it works again.  Can you please pursue with VSCode since you understand the authentication mechanism and I do not?  I think the fix for this [defect](https://github.com/microsoft/vscode/issues/137183) is a likely candidate for the breaking change.

**Comment by TheSharpieOne** [comment] 2022-01-05 19:24
I am running into this same issue with 1.62.3. As for `also is there a way to reset this?` You can go to "Manage Trusted Extensions" from the "Accounts" button (above the settings widget) at the bottom left then hover over your github name. It will open a menu allowing you to deselect extensions that have access.
![image](https://user-images.githubusercontent.com/664714/148276273-546400d3-ea02-4516-a2b8-65272bc23c13.png)
![image](https://user-images.githubusercontent.com/664714/148276378-63d641a4-301e-4af4-ba1e-206d67a06f53.png)

**Comment by jasonwilliams** [comment] 2022-02-08 10:58
@kglickman is this still broken?

**Comment by jasonwilliams** [comment] 2022-02-08 11:03
> Unfortunately this is an issue with the VS Code auth provider: [microsoft/vscode#112043](https://github.com/microsoft/vscode/issues/112043)
> 
> Until that issue is resolved, this unfortunately will be blocked (as I don't want to get into managing/storing secrets myself).

@eamodio I don't think this needs the "blocked" tags anymore as  [microsoft/vscode#112043](https://github.com/microsoft/vscode/issues/112043) has been resolved for quite some time.

**Comment by kglickman** [comment] 2022-02-08 12:47
This is working for me again in VSCode 1.64.0 but I have not gone back to figure out when it was fixed.

**Closed** 2022-07-13 03:37 UTC
Labels: feature
