### ISSUE TITLE
No view is registered with id: gitlens.views.launchpad after upgrading to 15.3.0

### ISSUE THREAD

**Issue by bradym** [gitkraken/vscode-gitlens#3477] opened 2024-08-16 21:36 UTC
### Description

Since updating to 15.3.0, any time the extension host restarts I get the message "No view is registered with id: gitlens.views.launchpad".

I've confirmed that reverting to 15.2.3 causes this to go away.

### GitLens Version

15.3.0

### VS Code Version

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.9.3-76060903-generic

### Git Version

git version 2.46.0

### Logs, Screenshots, Screen Captures, etc

![gitlens-no-view](https://github.com/user-attachments/assets/64fdd025-984a-413c-acca-44ee5d699672)

**Comment by eamodio** [comment] 2024-08-17 18:59
While I'm convinced this is a VS Code bug (as other issues seem to randomly appear on extension host restarts), I have seen this a couple of times but haven't ever been able to reproduce it -- to see if there is something we can do to avoid it.

Do you have any steps that reproduce the issue for you?

**Comment by bradym** [comment] 2024-08-19 17:18
When I submitted the ticket on Friday it was happening consistently any time I ran "Developer: Restart Extension Host" from the command palette (ctrl+shift+p) but today it's not. I have no idea what changed. :shrug:

**Comment by eamodio** [comment] 2024-08-19 22:01
@bradym Are you using the pre-release version of GitLens?

**Comment by bradym** [comment] 2024-08-19 22:50
Nope.
![image](https://github.com/user-attachments/assets/aad23790-0884-46d3-9c95-49c089324e37)

**Comment by eamodio** [comment] 2024-08-19 22:53
Hrm, then I'm not sure what changed -- did VS Code update? I can't reproduce this, nor have I seen it anymore recently.

**Comment by bradym** [comment] 2024-08-19 23:08
Nope, just compared the "Help -> About" contents to what I submitted on Friday and it's identical. Very weird. Guess this should be closed as can't reproduce.

**Comment by Rakpon5** [comment] 2024-08-19 23:18
[]()[]()

**Comment by eamodio** [comment] 2024-08-20 00:12
Thanks -- will close it for now, if you see it again please post and we can re-open.

**Closed by eamodio** 2024-08-20 00:12 UTC
Labels: bug

**Comment by robert-chiniquy** [comment] 2024-08-20 19:07
Just hit this one btw, found this ticket searching for the fix.

**Comment by eamodio** [comment] 2024-08-20 19:39
@robert-chiniquy if it's reproducible for you can you try the pre-release version to see if it changes anything? 

Also can you list the steps you are doing when you see it?

**Comment by holtbp** [comment] 2024-08-22 17:57
Ran into this issue and was able to get Copilot working again by switching to the pre-release version of GitLens, then restarting the GitHub Copilot extension

**Comment by CvBlixen** [comment] 2024-09-03 08:52
Thank you for the suggestions @eamodio ! 👍 

Switching to pre-release for both GitLens and Copilot made this disappear for me.

I'm not usually a pre-relase guy, so I would have preferred if this worked in the released versions, but not a big deal. 🙂

**Comment by robert-chiniquy** [comment] 2024-09-04 02:12
Been totally unable to repro.

**Comment by eamodio** [comment] 2024-09-04 02:30
@CvBlixen Thanks, It will be in the stable version tomorrow (if our change actually fixed it)
