### ISSUE TITLE
Cannot pull or force push if local branch name differs from remote branch name

### ISSUE THREAD

**Issue by sodevel** [gitkraken/vscode-gitlens#3327] opened 2024-05-29 13:37 UTC
### Description

Like the title says, i have a local branch named `umaster` that tracks the branch `master` on a remote, i cannot pull or force push that branch. However, a regular push does work.

### GitLens Version

15.0.4

### VS Code Version

Version: 1.89.1 (system setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.44.0.windows.1

**Comment by axosoft-ramint** [comment] 2024-05-29 16:06
@sodevel This seems related to [#3277](https://github.com/gitkraken/vscode-gitlens/issues/3277). There is a fix for this currently in the prerelease version of GitLens - would you mind switching over to the prerelease and seeing if you can still repro the bug?

You can switch to the pre-release edition of GitLens by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://github.com/gitkraken/vscode-gitlens/assets/67011668/15a6e337-f655-485c-9b11-7ef7bd67f254)

**Comment by sodevel** [comment] 2024-05-29 16:34
With that version pulling does work, but force-push still does not. The error message i receive sounds like it did a normal push, but the GitLens output channel shows a correct command line.

```
[2024-05-29 16:29:32.049] [GIT  ] [c:/git/xprivate/wxFormBuilder] git push --force-with-lease --force-if-includes upstream test/name-diff-diffed [*1021ms] (slow)
[2024-05-29 16:29:32.050] Git.push
Error: Unable to force push branch 'test/name-diff-diffed' to upstream because some refs failed to push or the push was rejected. The tip of the remote-tracking branch has been updated since the last checkout. Try pulling first.
```

**Comment by axosoft-ramint** [comment] 2024-05-29 16:37
Thanks. Is the result of the force push (and the output in that output channel) what you would expect to happen when force pushing in this particular case, or would you have expected it to succeed?

Trying to determine if it's just a messaging issue on the error notification or if it's a case of a force push failing that should have succeeded.

**Comment by sodevel** [comment] 2024-05-29 17:05
Well, i do expect the force push to happen, but using the command line `git push --force-with-lease --force-if-includes` in a terminal does fail as well. Just using `git push --force-with-lease` does succeed but i don't understand why the other one doesn't. No one changed the remote refs in between, the state my side knows about the remote is absolute identical to the current remote state, so to my understanding the `--force-if-includes` is fulfilled.

**Comment by axosoft-ramint** [comment] 2024-05-29 17:47
Hmmm, `--force-if-includes` also checks that the tip of the remote ref was 'integrated locally' - the push with this flag would fail if, for example, you had fetched but not checked out locally, some commits (i.e. applied them to your local history). Not saying that is the case here, but if it is, it would explain why the command fails. It is one of the gentlest forms of force push.

**Comment by axosoft-ramint** [comment] 2024-05-29 23:40
Since I'm not seeing any further bugs here, going to close this issue as a duplicate of 3277. Feel free to open a new one if, for example, you would like us to add a version of push without `--force-if-includes`.

**Closed by axosoft-ramint** 2024-05-29 23:40 UTC
Labels: bug, triage
