### ISSUE TITLE
copy SHA always remain the same

### ISSUE THREAD

**Issue by adndyxu** [gitkraken/vscode-gitlens#1868] opened 2022-03-02 10:23 UTC
- GitLens Version: 12.0.0
- Git Version: git version 2.30.1 (Apple Git-130)

- VSCode Version: 1.64.2 (Universal)
- OS Version:Darwin arm64 20.6.0

Steps to Reproduce:

1.open commits
2.copy SHA
3.every commits tend to be one SHA value

### rollback to 11.7.0, everything is fine

**Comment by eamodio** [comment] 2022-03-02 15:24
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1866

**Closed** 2022-03-02 15:24 UTC
Labels: potential-bug, triage
