### ISSUE TITLE
[Branches view] Missing status and overlay indicator for unpublished branch

### ISSUE THREAD

**Issue by chr7** [gitkraken/vscode-gitlens#1831] opened 2022-02-24 11:05 UTC
- GitLens Version: v11.7.0
- Git Version: 2.32.0.windows.1

- VSCode Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

I created a new local branch a while ago. As I haven't published it yet, it should have according to the [documentation](https://github.com/gitkraken/vscode-gitlens#branches-view-) two indicators: a green one for unpushed changes and an up arrow with the plus sign to indicate that the branch hasn't yet been published to an upstream remote. Both are missing:

![image](https://user-images.githubusercontent.com/7242780/155512560-e884f2c1-b506-4c93-a8ec-bbaa3d9ef058.png)

**Comment by mopatches** [comment] 2024-05-17 21:19
Relatedly, it appears that the dark red color for branches that are missing upstream has also gone missing in a recent release.

**Comment by eamodio** [comment] 2024-05-18 17:23
Duplicate of #3302

**Closed by eamodio** 2024-05-18 17:23 UTC
Labels: bug, triage
