### ISSUE TITLE
Gitlens Badge Notification

### ISSUE THREAD

**Issue by sclel016** [gitkraken/vscode-gitlens#1590] opened 2021-07-26 16:10 UTC
- GitLens Version: 11.6.0
- Git Version: 2.31.1
- VSCode Version: 1.58.2
- OS Version: Fedora 34

Steps to Reproduce:

1. Install Gitlens
2. See badge notification to connect to Github
3. No way to remove badge notification in Settings

Hi,

Gitlens is great, but I don't need the extra functionality offered by Github integration. There seems to be no way to disable the badge notification asking me to connect to Github. Is this a bug or expected behavior? Reviewing past issues, it seems that #1208 reported the issue but the behavior is still present.

Thanks!

![gitlens_issue](https://user-images.githubusercontent.com/11709587/127022017-3ed0999e-a0ae-4b55-b8ee-e6ab7732d285.png)

**Comment by eamodio** [comment] 2021-12-22 08:34
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1506

**Closed by eamodio** 2021-12-22 08:34 UTC
Labels: duplicate
