### ISSUE TITLE
file history view support filter exclude unchange commits

### ISSUE THREAD

**Issue by tjx666** [gitkraken/vscode-gitlens#2673] opened 2023-05-12 09:20 UTC
There are many no changes commits in file histoy view:

![image](https://github.com/gitkraken/vscode-gitlens/assets/41773861/12ca0089-88e4-4154-a4f1-9756001974fd)

Just expect can list like vscode builtin timeline:

![image](https://github.com/gitkraken/vscode-gitlens/assets/41773861/c7902892-f2ff-4005-b57b-9e4dbac13312)

**Comment by eamodio** [comment] 2023-10-21 16:15
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2104 which has been completed

**Closed by eamodio** 2023-10-21 16:15 UTC
Labels: feature
