### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by capaj** [gitkraken/vscode-gitlens#2061] opened 2022-06-29 19:03 UTC
- GitLens Version: v12.1.1
- Git Version:  git version 2.34.1

- VSCode Version: 1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
- OS Version: ubuntu 22.0

sorry, just a stack trace:
```
TypeError: Cannot read properties of undefined (reading 'fsPath')
    at Ke.getRelativePath (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/env/node/git/localGitProvider.ts:742:56)
    at Ke.getAbsoluteUri (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/env/node/git/localGitProvider.ts:684:29)
    at Object.getAbsoluteUri (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/git/gitProviderService.ts:887:19)
    at Function.fromFile (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/git/gitUri.ts:229:15)
    at new FileRevisionAsCommitNode (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/views/nodes/fileRevisionAsCommitNode.ts:37:9)
    at /home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/views/nodes/lineHistoryNode.ts:142:10
    at filterMap (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/system/iterable.ts:90:18)
    at m.next (<anonymous>)
    at insertDateMarkers (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/views/nodes/helpers.ts:28:13)
    at Er.next (<anonymous>)
    at E.getChildren (/home/capaj/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/views/nodes/lineHistoryNode.ts:138:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at b.fetchChildrenNodes (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:19816)
    at b.getChildren (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:16035)
```

Steps to Reproduce:

1. not sure

**Comment by thmudersfc** [comment] 2022-07-04 07:59
I also get this error message.
MacOS 12.4 (21F79) Apple Silicon
VS Code version 1.68.1 30d9c6cd9483b2cc586687151bcbcd635f373630
Git version 2.37.0
GitLens Version 12.1.1

Line history is not working, when I click on Line history refresh button this error message appears.

**Comment by eamodio** [comment] 2022-07-11 18:50
Duplicate of #1896

**Closed by eamodio** 2022-07-11 18:50 UTC
Labels: duplicate
