### ISSUE TITLE
GitLens won't start

### ISSUE THREAD

**Issue by Spongman** [gitkraken/vscode-gitlens#1842] opened 2022-02-28 19:42 UTC
- GitLens Version: v12.0.0
- Git Version: git version 2.18.4
- VSCode Version: 1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
- OS Version: win10

Steps to Reproduce:

1. restart vscode

![image](https://user-images.githubusercontent.com/1088194/156047869-496aa439-fb30-469f-965c-8bc6ae051678.png)

was working fine 10 minutes ago.

**Comment by eamodio** [comment] 2022-02-28 19:54
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1836 which will be fixed in a couple of minutes.

**Closed by eamodio** 2022-02-28 19:54 UTC
Labels: potential-bug, triage
