### ISSUE TITLE
Cannot read properties of undefined (reading 'repoPath')

### ISSUE THREAD

**Issue by ophers** [gitkraken/vscode-gitlens#2501] opened 2023-02-10 17:10 UTC
### Description

Running in WSL.
I'm on the pre-release track. The extension was automatically updated to v2023.2.1004.
And then disaster hit. the Commits pane is always blank, although the title bar shows the branch and ahead/behind commits.
![image](https://user-images.githubusercontent.com/11839190/218151855-016679cc-8bac-4813-b079-c42665e12787.png)
Pressing "refresh" button gives this error message:
> Cannot read properties of undefined (reading 'repoPath')
![image](https://user-images.githubusercontent.com/11839190/218153385-44277a90-5405-445d-b059-525bf678e892.png)

### GitLens Version

v2023.2.1004

### VS Code Version

Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

### Git Version

git version 2.31.1

### Logs, Screenshots, Screen Captures, etc

[GitLens (Git) Debug output.txt](https://github.com/gitkraken/vscode-gitlens/files/10709686/GitLens.Git.Debug.output.txt)
[GitLens Debug output.txt](https://github.com/gitkraken/vscode-gitlens/files/10709687/GitLens.Debug.output.txt)

**Comment by ophers** [comment] 2023-02-10 17:14
reverted to version `v2023.2.904` and it works correctly.

**Comment by eamodio** [comment] 2023-02-10 17:22
Thanks for the report -- this is a duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2499

A new pre-release will be out shortly with the fix.

**Closed by eamodio** 2023-02-10 17:22 UTC
Labels: potential-bug, triage
