### ISSUE TITLE
Regression of #958 for main icon

### ISSUE THREAD

**Issue by grgar** [gitkraken/vscode-gitlens#3206] opened 2024-03-29 22:39 UTC
### Description

One icon, the GitLens main editor action icon, does not adapt to the foreground icon colour.

Apart from the main icon, the other icons from #958 still work changing colour.

<details>
<summary>Versions</summary>

### GitLens Version

v2024.3.2805 (pre-release)

### VS Code Version

Version: 1.88.0-insider
Commit: aa25485166449aa0f9eb8ebd8d0b70376108633c
Date: 2024-03-28T22:11:13.430Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

### Git Version

git version 2.44.0

</details>

### Logs, Screenshots, Screen Captures, etc

With the following in settings.json to highlight the problem

```json
	"workbench.colorCustomizations": {
		"icon.foreground": "#ff0000"
```

the icons turn red except one:

<img width="258" src="https://github.com/gitkraken/vscode-gitlens/assets/191085/f84b452d-0353-40a1-acc6-372e96b657d5">

**Comment by eamodio** [comment] 2024-03-31 03:03
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/3143

**Closed by eamodio** 2024-03-31 03:03 UTC
Labels: bug, triage
