### ISSUE TITLE
Constant prompt "Your github credentials do not have the required access"

### ISSUE THREAD

**Issue by sirianni** [gitkraken/vscode-gitlens#1935] opened 2022-03-29 16:48 UTC
Every time I open a project I get this popup
![image](https://user-images.githubusercontent.com/381302/160663877-66f9458a-cb82-4179-8cfb-090c7315cd5a.png)

> Your 'github' credentials do not have the required access. Would you like to try reauthenticating to provide additional access?

When I click `Reauthenticate` nothing happens.  Seems related to https://github.com/gitkraken/vscode-gitlens/issues/1208

**Comment by eamodio** [comment] 2022-03-31 06:16
@sirianni Typically that error happens when the token access you have provided to GitLens doesn't have the organization (or something) to access the repository you are opening. Can you check that the organization of the repository is granted when you auth with GitHub?

**Comment by MoonLiightz** [comment] 2022-03-31 07:56
In my case the problem occurs in every repo that is in my personal "namespace". This requires permissions for the organizations? I have clicked on "Connect to GitHub" via the "Hovers" function and get spammed with the above error message every time I hover.
In the OAuth redirect url you can see the following scope 
```
scope=read:user+repo+user:email
```

**Comment by sirianni** [comment] 2022-04-01 14:26
> the token access you have provided to GitLens

I can't see what token I've provided to GitLens.  I've spent quite a bit of time hunting through the extension settings and cannot find where to configure this.  Also, as mentioned, when I click `Reauthenticate` it doesn't prompt me for a token or open a browser, etc.

**Comment by eamodio** [comment] 2022-04-13 05:30
@sirianni @MoonLiightz I believe GitLens 12.0.6 should resolve this issue. Please let me know if it persists. It should happen 1 more time, and then once you re-auth (which should work this time) it should be resolved.

**Comment by eamodio** [comment] 2022-04-13 18:02
@MoonLiightz Can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channels.

Thank you!

**Comment by MoonLiightz** [comment] 2022-04-14 07:17
Of course.

Log directly after a click on "Reauthenticate":

<details>
<summary>Log</summary>

```
[2022-04-14 06:40:41.664] [  27e] GitProviderService.getBlame — s=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), e={"uri":{"$mid":1,"fsPath":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","external":"file://<ANONYMIZED: local path to repository>/internal/appcli/command.go","path":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","scheme":"file"},"fileName":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","isUntitled":false,"languageId":"go","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":94}
[2022-04-14 06:40:41.664] [  27f] LocalGitProvider.getBlame — e=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), t={"uri":{"$mid":1,"fsPath":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","external":"file://<ANONYMIZED: local path to repository>/internal/appcli/command.go","path":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","scheme":"file"},"fileName":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","isUntitled":false,"languageId":"go","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":94}
[2022-04-14 06:40:41.665] [  27f] LocalGitProvider.getBlame Cache hit: 'blame'
[2022-04-14 06:40:41.665] [  27f] LocalGitProvider.getBlame completed • 0 ms
[2022-04-14 06:40:41.665] [  27e] GitProviderService.getBlame completed • 0 ms
[2022-04-14 06:40:41.668] GitCodeLensProvider.provideCodeLenses: — 2 symbol(s) found
```

</details>

A bit more logging after "normal" work:

<details>
<summary>Log</summary>

```
[2022-04-14 06:42:15.248] [  40a] GitProviderService.getRemotesWithProviders — s=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.248] [  40b] GitProviderService.getRepository — s=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.248] [  40b] GitProviderService.getRepository returned <ANONYMIZED: local path to repository> • 0 ms
[2022-04-14 06:42:15.249] [  40a] GitProviderService.getRemotesWithProviders completed • 0 ms
[2022-04-14 06:42:15.249] [  40c] GitHubRemote.connect
[2022-04-14 06:42:15.265] [  40d] Repository(<ANONYMIZED: local path to repository>).fireChange — providers
[2022-04-14 06:42:15.266] [  40d] Repository(<ANONYMIZED: local path to repository>).fireChange completed • 0 ms
[2022-04-14 06:42:15.266] [  40e] GitProviderService.resetCaches — providers
[2022-04-14 06:42:15.266] [  40f] LocalGitProvider.resetCaches — providers
[2022-04-14 06:42:15.266] [  40f] LocalGitProvider.resetCaches completed • 0 ms
[2022-04-14 06:42:15.266] [  410] VslsGitProvider.resetCaches — providers
[2022-04-14 06:42:15.266] [  410] VslsGitProvider.resetCaches completed • 0 ms
[2022-04-14 06:42:15.266] [  411] GitHubGitProvider.resetCaches — providers
[2022-04-14 06:42:15.266] [  411] GitHubGitProvider.resetCaches completed • 0 ms
[2022-04-14 06:42:15.266] [  40e] GitProviderService.resetCaches completed • 0 ms
[2022-04-14 06:42:15.266] [  412] LineAnnotationController.refresh
[2022-04-14 06:42:15.266] [  413] GitProviderService.getRichRemoteProvider — s=origin, e={"includeDisconnected":false}
[2022-04-14 06:42:15.266] [  414] GitProviderService.getRichRemoteProvider — s=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.266] [  40c] GitHubRemote.connect completed • 17 ms
[2022-04-14 06:42:15.266] [  413] GitProviderService.getRichRemoteProvider completed • 0 ms
[2022-04-14 06:42:15.266] [  414] GitProviderService.getRichRemoteProvider completed • 0 ms
[2022-04-14 06:42:15.266] [  415] GitProviderService.getPullRequestForCommit — s=02c4910a3da014074bc60bb11e69b6107c50a758, e=GitHub (github.com)
[2022-04-14 06:42:15.266] [  416] GitHubRemote.getPullRequestForCommit — A=02c4910a3da014074bc60bb11e69b6107c50a758
[2022-04-14 06:42:15.266] [  417] GitHubRemote.getPullRequestForCommitCore — A=02c4910a3da014074bc60bb11e69b6107c50a758
[2022-04-14 06:42:15.266] [  418] GitHubApi.getPullRequestForCommit — i=GitHub (github.com), <token>, o=MoonLiightz, s=magic-home, u=02c4910a3da014074bc60bb11e69b6107c50a758, c={"baseUrl":"https://github.com/api"}
[2022-04-14 06:42:15.367] [  412] LineAnnotationController.refresh • 1 pull request queries took too long (over 100 ms)
[2022-04-14 06:42:15.368] [  412] LineAnnotationController.refresh completed • selection(s)=[39-39] • 101 ms
[2022-04-14 06:42:15.441] [ 1049] [GITHUB] POST /graphql query getPullRequestForCommit • 174 ms
[2022-04-14 06:42:15.441] [  418] GitHubApi.getPullRequestForCommit 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.441] [  418] GitHubApi.getPullRequestForCommit — failed • 175 ms
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.441] [  417] GitHubRemote.getPullRequestForCommitCore 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.441] [  41a] GitHubRemote.handleClientException
[2022-04-14 06:42:15.441] [  41a] GitHubRemote.handleClientException completed • 0 ms
[2022-04-14 06:42:15.441] [  417] GitHubRemote.getPullRequestForCommitCore completed • 175 ms
[2022-04-14 06:42:15.441] [  416] GitHubRemote.getPullRequestForCommit completed • 175 ms
[2022-04-14 06:42:15.441] [  415] GitProviderService.getPullRequestForCommit completed • 175 ms
[2022-04-14 06:42:15.442] [  412] LineAnnotationController.refresh • 1 pull request queries completed; refreshing...
[2022-04-14 06:42:15.442] [  41b] LineAnnotationController.refresh
[2022-04-14 06:42:15.442] [  41b] LineAnnotationController.refresh completed • selection(s)=[39-39] • 0 ms
[2022-04-14 06:42:15.517] Repository(<ANONYMIZED: local path to repository>) firing changes=providers
[2022-04-14 06:42:15.598] [  41c] LineHoverController.provideDetailsHover — e=Uri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go), t=39:77
[2022-04-14 06:42:15.598] [  41d] LineHoverController.provideChangesHover — e=Uri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go), t=39:77
[2022-04-14 06:42:15.598] [  41e] GitProviderService.getRemotesWithProviders — s=<ANONYMIZED: local path to repository>, e={"sort":true}
[2022-04-14 06:42:15.598] [  41f] GitProviderService.getRepository — s=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.598] [  41f] GitProviderService.getRepository returned <ANONYMIZED: local path to repository> • 0 ms
[2022-04-14 06:42:15.598] [  420] GitProviderService.getDiffForLine — s=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), e=39, t=43afb441a5ce0681da5a2c7482521f4d89f2dec1, i=undefined
[2022-04-14 06:42:15.598] [  421] LocalGitProvider.getDiffForLine — e=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), t=39, i=43afb441a5ce0681da5a2c7482521f4d89f2dec1, o=undefined
[2022-04-14 06:42:15.598] [  422] LocalGitProvider.getDiffForFile — e=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), t=43afb441a5ce0681da5a2c7482521f4d89f2dec1, i=undefined
[2022-04-14 06:42:15.598] [  41e] GitProviderService.getRemotesWithProviders completed • 0 ms
[2022-04-14 06:42:15.598] [ 1059] Hovers.getAutoLinkedIssuesOrPullRequests — message=<message>
[2022-04-14 06:42:15.598] [  424] GitProviderService.getRichRemoteProvider — s=origin
[2022-04-14 06:42:15.598] [ 1061] Hovers.getPullRequestForCommit — ref=02c4910a3da014074bc60bb11e69b6107c50a758
[2022-04-14 06:42:15.598] [  426] GitProviderService.getRichRemoteProvider — s=origin, e={"includeDisconnected":true}
[2022-04-14 06:42:15.598] [  427] VslsController.maybeGetPresence — <ANONYMIZED: my GitHub mail address>
[2022-04-14 06:42:15.598] [  428] VslsController.getContactPresence — e=<ANONYMIZED: my GitHub mail address>
[2022-04-14 06:42:15.598] [  429] VslsController.getContact — e=<ANONYMIZED: my GitHub mail address>
[2022-04-14 06:42:15.598] [  424] GitProviderService.getRichRemoteProvider completed • 0 ms
[2022-04-14 06:42:15.598] [  426] GitProviderService.getRichRemoteProvider completed • 0 ms
[2022-04-14 06:42:15.598] [  429] VslsController.getContact completed • 0 ms
[2022-04-14 06:42:15.598] [  422] LocalGitProvider.getDiffForFile Cache hit: 'diff:43afb441a5ce0681da5a2c7482521f4d89f2dec1'
[2022-04-14 06:42:15.598] [  42a] Autolinks.getIssueOrPullRequestLinks — <message>, 250
[2022-04-14 06:42:15.598] [  42b] GitProviderService.getPullRequestForCommit — s=02c4910a3da014074bc60bb11e69b6107c50a758, e=GitHub (github.com), t={"timeout":250}
[2022-04-14 06:42:15.598] [  42c] GitHubRemote.getPullRequestForCommit — A=02c4910a3da014074bc60bb11e69b6107c50a758
[2022-04-14 06:42:15.598] [  42d] GitHubRemote.getPullRequestForCommitCore — A=02c4910a3da014074bc60bb11e69b6107c50a758
[2022-04-14 06:42:15.598] [  428] VslsController.getContactPresence completed • 0 ms
[2022-04-14 06:42:15.598] [  42a] Autolinks.getIssueOrPullRequestLinks completed • 0 ms
[2022-04-14 06:42:15.598] [ 1059] Hovers.getAutoLinkedIssuesOrPullRequests completed • 0 ms
[2022-04-14 06:42:15.598] [  42e] GitHubApi.getPullRequestForCommit — i=GitHub (github.com), <token>, o=MoonLiightz, s=magic-home, u=02c4910a3da014074bc60bb11e69b6107c50a758, c={"baseUrl":"https://github.com/api"}
[2022-04-14 06:42:15.600] [  422] LocalGitProvider.getDiffForFile completed • 2 ms
[2022-04-14 06:42:15.600] [  427] VslsController.maybeGetPresence completed • 2 ms
[2022-04-14 06:42:15.600] [  421] LocalGitProvider.getDiffForLine completed • 2 ms
[2022-04-14 06:42:15.600] [  420] GitProviderService.getDiffForLine completed • 2 ms
[2022-04-14 06:42:15.603] [  41d] LineHoverController.provideChangesHover completed • 4 ms
[2022-04-14 06:42:15.788] [ 1071] [GITHUB] POST /graphql query getPullRequestForCommit • 189 ms
[2022-04-14 06:42:15.788] [  42e] GitHubApi.getPullRequestForCommit 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.788] [  42e] GitHubApi.getPullRequestForCommit — failed • 189 ms
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.788] [  42d] GitHubRemote.getPullRequestForCommitCore 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.788] [  430] GitHubRemote.handleClientException
[2022-04-14 06:42:15.788] [  430] GitHubRemote.handleClientException completed • 0 ms
[2022-04-14 06:42:15.788] [  42d] GitHubRemote.getPullRequestForCommitCore completed • 189 ms
[2022-04-14 06:42:15.788] [  42c] GitHubRemote.getPullRequestForCommit completed • 189 ms
[2022-04-14 06:42:15.788] [  42b] GitProviderService.getPullRequestForCommit completed • 189 ms
[2022-04-14 06:42:15.788] [ 1061] Hovers.getPullRequestForCommit completed • 190 ms
[2022-04-14 06:42:15.788] [  431] GitProviderService.getRichRemoteProvider — s=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.788] [  431] GitProviderService.getRichRemoteProvider completed • 0 ms
[2022-04-14 06:42:15.788] [  432] GitHubRemote.getAccountForCommit — A=02c4910a3da014074bc60bb11e69b6107c50a758, k={"avatarSize":64}
[2022-04-14 06:42:15.788] [  433] GitHubApi.getAccountForCommit — i=GitHub (github.com), <token>, o=MoonLiightz, s=magic-home, u=02c4910a3da014074bc60bb11e69b6107c50a758, c={"avatarSize":64,"baseUrl":"https://github.com/api"}
[2022-04-14 06:42:15.968] [ 1076] [GITHUB] POST /graphql query getAccountForCommit • 179 ms
[2022-04-14 06:42:15.968] [  433] GitHubApi.getAccountForCommit 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.969] [  433] GitHubApi.getAccountForCommit — failed • 180 ms
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.969] [  432] GitHubRemote.getAccountForCommit 
Error: Your 'github' credentials do not have the required access
[2022-04-14 06:42:15.969] [  435] GitHubRemote.handleClientException
[2022-04-14 06:42:15.969] [  435] GitHubRemote.handleClientException completed • 0 ms
[2022-04-14 06:42:15.969] [  432] GitHubRemote.getAccountForCommit completed • 180 ms
[2022-04-14 06:42:15.969] [  436] Autolinks.linkify — <text>, t=true, i=1, o=undefined, d=0
[2022-04-14 06:42:15.969] [  436] Autolinks.linkify completed • 0 ms
[2022-04-14 06:42:15.969] [  437] GitProviderService.getRevisionUri — s=43afb441a5ce0681da5a2c7482521f4d89f2dec1, e=internal/appcli/command.go, t=<ANONYMIZED: local path to repository>
[2022-04-14 06:42:15.969] [  437] GitProviderService.getRevisionUri completed • 0 ms
[2022-04-14 06:42:15.969] [  438] GitProviderService.getRevisionUri — s=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository> sha=02c4910a3da014074bc60bb11e69b6107c50a758)
[2022-04-14 06:42:15.969] [  438] GitProviderService.getRevisionUri completed • 0 ms
[2022-04-14 06:42:15.969] [  41c] LineHoverController.provideDetailsHover completed • 371 ms
[2022-04-14 06:42:18.388] [  439] GitProviderService.getBlame — s=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), e={"uri":{"$mid":1,"fsPath":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","external":"file://<ANONYMIZED: local path to repository>/internal/appcli/command.go","path":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","scheme":"file"},"fileName":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","isUntitled":false,"languageId":"go","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":94}
[2022-04-14 06:42:18.388] [  43a] LocalGitProvider.getBlame — e=GitUri(file://<ANONYMIZED: local path to repository>/internal/appcli/command.go repoPath=<ANONYMIZED: local path to repository>), t={"uri":{"$mid":1,"fsPath":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","external":"file://<ANONYMIZED: local path to repository>/internal/appcli/command.go","path":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","scheme":"file"},"fileName":"<ANONYMIZED: local path to repository>/internal/appcli/command.go","isUntitled":false,"languageId":"go","version":1,"isClosed":false,"isDirty":false,"eol":1,"lineCount":94}
```

</details>

The "GitLens (Git)" log has stayed empty all the way.

Small note, I anoymized the local path to the repository as well as my mail address in the log. It should be well recognizable.

If I can help further please let me know.

**Comment by GoldenMaximo** [comment] 2022-06-13 19:54
I'm having the same issue with `v12.0.7`.

```
[2022-06-13 19:46:56.927] [GIT  ] [/Users/gustavomaximo/[redacted]] git diff --no-ext-diff --minimal -U0 -M --diff-filter=M 0000000000000000000000000000000000000000- -- src/components/[redacted].jsx • Command failed: /usr/local/bin/git -c core.quotepath=false -c color.ui=false -c color.diff=false diff --no-ext-diff --minimal -U0 -M --diff-filter=M 0000000000000000000000000000000000000000- -- src/components/[redacted].jsx • bad revision '0000000000000000000000000000000000000000-' • 12 ms

[2022-06-13 19:47:08.240] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:08.240] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:08.489] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:08.489] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:09.063] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:09.063] ee.graphql
Error: Your 'github' credentials do not have the required access
[2022-06-13 19:47:09.655] ee.graphql
```

I've already granted access to the organization the code belongs to with my SSH key:
![Screen Shot 2022-06-13 at 4 51 17 PM](https://user-images.githubusercontent.com/51284438/173434105-73235989-41dd-4afe-a4ea-106ce580bbda.png)

**Comment by Nico26-sw** [comment] 2022-06-30 12:38
Hi,
Same issue for me with v12.1.1
I always have the "Your 'github' credentials do not have the required access. Would you like to try reauthenticating to provide additional access?" popup at start, and every times gitlens tries to access Github information. Clicking on the "Reauthenticate" button looks doing nothing.
I think I have the issue since my organization moved to Github SSO, but like @GoldenMaximo I've authorized access with my SSH key.

**Comment by yogithesymbian** [comment] 2022-07-21 12:02
<img width="833" alt="Screen Shot 2022-07-21 at 7 58 03 PM" src="https://user-images.githubusercontent.com/28316296/180208327-ea5657ab-8bf9-4f27-b515-621e4113c495.png">
i have same issue , i have alr tried to **re-authentication** every time i save file or open a file the popup always on appears.

> git lens insider latest version.

**Comment by rjain-mural** [comment] 2022-07-21 21:02
@yogithesymbian I have the same exact issue that you are seeing. Also on macOS and get the message in VSCode as well as that "rich integration" popup

**Comment by jnpwly** [comment] 2022-07-21 23:43
Is this related to https://github.com/gitkraken/vscode-gitlens/issues/2067? And is there any significance that this seems to happen when there's a GitHub Enterprise account (vs. a "regular", non-Enterprise account) being used for the GitLens integration?

**Comment by grumBit** [comment] 2022-07-22 01:37
I was having similar problems with constant prompting of "Your github credentials do not have the required access". 

I got around it by disabling the `GitLens (Insiders)` extension and enabling `GitLens — Git supercharged` instead. Not sure if this will help anyone else though.

**Comment by grumBit** [comment] 2022-07-22 01:58
> I got around it by disabling the `GitLens (Insiders)` extension and enabling `GitLens — Git supercharged` instead. Not sure if this will help anyone else though.

👆 When I did the above, I also followed the prompt to reload VS Code, after which everything temporarily worked, but the problem returned. I discovered `GitLens (Insiders)` had been re-enabled (I'm 99% sure I didn't do that!). I disabled it again and instead of reloading, I quit VS Code and restarted it, and now everything seems to be ok. 🤞

**Comment by Nico26-sw** [comment] 2022-07-22 08:03
OK, thanks for the tips @grumBit , I disabled `GitLens — Git supercharged`, reenabled it, restarted VS Code and now it looks OK :man_shrugging:

**Comment by klawrawkz** [comment] 2022-07-28 21:43
Hi all, my name is klawarkz. I'm fine. How are you?

Thanks for the suggestion @grumBit. Here's what I get when I install *GitLens 'supercharged'*:

![image](https://user-images.githubusercontent.com/48074223/181641768-5ab9da12-0d4d-4e80-a45c-13022635c816.png)

Pretty lame. Say, why the reliance on the 'gitkraken.gitkraken authentication' extension anyway? It seems to me that if there is any value in using such auth that you should provide this as a separate extension. I'd like to have a choice in the matter rather than GitLense covertly pushing this dependency into my environment without asking.

As it stands, GitLense is inoperable, and hence, **_useless._** I feel certain that this is not what is intended. Is there some hidden value associated with this auth extension that is not apparent? Clearly I'm not experiencing any of the "benefits" as I can't use the extension at this point.

Hope you are well.

klaw

**Comment by yogithesymbian** [comment] 2022-07-28 22:51
I dunno why but now its work like a normal, i just disable and enable and restart vscode(reload) still got the issue until i delete the `.git folder because i cant work` , but when i restart my device (laptop) 
and try again;  currently its normal . I use gitlens ( Insider ) `v2022.7.2805`

**Comment by grumBit** [comment] 2022-07-29 00:52
> I dunno why but now its work like a normal, i just disable and enable and restart vscode(reload) still got the issue until i delete the `.git folder because i cant work` , but when i restart my device (laptop) and try again; currently its normal . I use gitlens ( Insider ) `v2022.7.2805`

`gitlens ( Insider )` was the one that was causing me issues. Once I moved to `GitLens — Git supercharged`, I stopped getting the credentials problem.

**Comment by bernardofbbragameli** [comment] 2022-08-02 17:53
This error would show for me when I was off VPN, see this issue where it was fixed https://github.com/gitkraken/vscode-gitlens/issues/2117
Could be the case for some of you, feel free to thumbs up if it was the case or thumbs down if it was not

**Comment by eamodio** [comment] 2022-08-29 03:48
I believe these issues should be resolved in the latest insiders builds -- can any of you try to see if the issue is still reproducible in the GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). 

Please be sure to disable or uninstall the stable version of GitLens first. Thanks!

**Closed** 2022-08-29 03:48 UTC
Labels: bug, pending-release, needs-verification, area-integrations
