### ISSUE TITLE
VS Code's Editor "jumping" with any code changes when there is not (at least) one Git committed activity

### ISSUE THREAD

**Issue by scandeiro** [gitkraken/vscode-gitlens#1007] opened 2020-04-23 03:48 UTC
My setup:

- GitLens Version: 10.2.1
- VSCode Version: 1.43.0
- OS Version: Fedora 31 (x64)

Steps to Reproduce:

1. Init any project with Git and GitLens Extension already configured and do not commit/push anything
2. Open any file and start typing anything
3. Just see a "ghost" line before the first line on VS Code's Editor starts to jump

![bug](https://user-images.githubusercontent.com/6067306/80056710-317aa380-84fb-11ea-945b-06ca7a9eaf50.gif)

Important Notes:

1. I tested the same approach with Git History Extension off and GitLens Extension on, even after restarting the VS Code, the problem continues.
2. I tested the same approach with Git History Extension on and GitLens Extension off, even after restarting the VS Code, the problem goes away.

**Comment by shaunmoss** [comment] 2020-12-05 09:27
I have the same issue, really distracting having everything jumping around while I code.

**Comment by RodrigoGroener** [comment] 2022-03-02 17:20
+1

**Comment by eamodio** [comment] 2022-03-02 17:37
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1742

**Closed by eamodio** 2022-03-02 17:37 UTC
Labels: potential-bug
