### ISSUE TITLE
Solution not working: How do I stop gitlens from asking me to sign in github? 

### ISSUE THREAD

**Issue by kgfly** [gitkraken/vscode-gitlens#1834] opened 2022-02-25 10:28 UTC
https://github.com/gitkraken/vscode-gitlens/issues/1233 provides solution. However, it does not work. My setting file only has

{
  "gitlens.currentLine.pullRequests.enabled": false,
  "gitlens.hovers.autolinks.enhanced": false,
  "gitlens.hovers.pullRequests.enabled": false,
  "gitlens.statusBar.pullRequests.enabled": false,
  "gitlens.views.branches.pullRequests.enabled": false,
  "gitlens.views.branches.pullRequests.showForBranches": false,
  "gitlens.views.branches.pullRequests.showForCommits": false,
  "gitlens.views.commits.pullRequests.enabled": false,
  "gitlens.views.commits.pullRequests.showForBranches": false,
  "gitlens.views.commits.pullRequests.showForCommits": false,
  "gitlens.views.contributors.pullRequests.enabled": false,
  "gitlens.views.contributors.pullRequests.showForCommits": false,
  "gitlens.views.searchAndCompare.pullRequests.showForCommits": false,
  "gitlens.views.searchAndCompare.pullRequests.enabled": false,
  "gitlens.views.repositories.pullRequests.showForCommits": false,
  "gitlens.views.repositories.pullRequests.showForBranches": false,
  "gitlens.views.repositories.pullRequests.enabled": false,
  "gitlens.views.remotes.pullRequests.showForCommits": false,
  "gitlens.views.remotes.pullRequests.showForBranches": false,
  "gitlens.views.remotes.pullRequests.enabled": false
}

But vscode keep asks for sign in, etc

![image](https://user-images.githubusercontent.com/12282281/155699386-7502fb12-c091-4737-bf95-676c87311d6d.png)

So how do I stop gitlens from asking me to sign in git hub? 

OS: Windows 11
VS code: 1.64.2
gitlen: v11.7.0

Thanks.

**Comment by eamodio** [comment] 2022-02-28 18:21
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1208 which is now released in GitLens 12.

**Closed by eamodio** 2022-02-28 18:21 UTC
Labels: feature, triage
