### ISSUE TITLE
Gitea remote encodes hash char

### ISSUE THREAD

**Issue by Lorite** [gitkraken/vscode-gitlens#2448] opened 2023-01-13 14:06 UTC
### Description

1. Add the following lines to the user settings:
```
"gitlens.remotes": [
      { "domain": "git.devops", "type": "Gitea", "protocol": "http" }
    ], 
```
2. Run the command "GitLens: Open File on Remote"
3. The browser opens, but the link contains this at the end: _file.hpp%23L25_ when the expected is _file.hpp#L25_ 

### GitLens Version

13.2.0

### VS Code Version

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-58-generic snap
Sandboxed: No

### Git Version

git version 2.25.1

**Comment by WofWca** [comment] 2023-03-25 08:33
Duplicate of #2252

**Closed** 2023-03-29 16:15 UTC
Labels: bug
