### ISSUE TITLE
toggle code lens does not work with `gitlens.codeLens.enabled == false`

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [gitkraken/vscode-gitlens#2548] opened 2023-03-07 15:16 UTC
### Description

Environment:
Windows 11, WSL2 ubuntu

Issue:
I like Codelens, and I do use it once in a while. But usually, I keep it off to prevent it from distracting me. So far, I've been toggling it off every time I'm annoyed by it through the "Toggle Git Codelens" command. But I've been doing it so often that I decided it would make more sense to disable it by default, and toggle it on when I need it.

Looking at the documentation here:
https://help.gitkraken.com/gitlens/gitlens-settings/

gitlens.codeLens.enabled

> Specifies whether to provide any Git CodeLens, by default. Use the Toggle Git CodeLens command (gitlens.toggleCodeLens) to toggle the Git CodeLens on and off for the current window

This seems like exactly what I needed, set gitlens.codeLens.enabled to false, and toggle Codelens on when I need it.

Sadly, when I try that, the toggling command doesn't do anything, Codelens does not appear. The output for Gitlens is also empty.

### GitLens Version

v13.3.2

### VS Code Version

Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

 git --version git version 2.35.3

**Comment by d13** [comment] 2023-03-07 15:23
duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2549

**Closed by d13** 2023-03-07 15:23 UTC
Labels: duplicate
