### ISSUE TITLE
date fomat not correct on hover

### ISSUE THREAD

**Issue by wu0407** [gitkraken/vscode-gitlens#1849] opened 2022-03-01 07:14 UTC
- GitLens Version: v12.0.0
- Git Version:  git version 2.29.2.windows.3

- VSCode Version: 
```
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```
- OS Version:  windows 10 pro 

Steps to Reproduce:

1.  change `Regional Format` to chinese in windows settings
![WXWorkCapture_16461182409046](https://user-images.githubusercontent.com/7602218/156122140-e9cc4adb-66ce-4b63-8c3e-8226f78b1be9.png)
![WeCom Screenshot_20220301152115](https://user-images.githubusercontent.com/7602218/156123186-5a20ce0b-ef3e-4aed-bd5e-ff4685da6d4a.png)

**Comment by eamodio** [comment] 2022-03-02 21:04
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1859

**Closed by eamodio** 2022-03-02 21:04 UTC
Labels: potential-bug, triage
