### ISSUE TITLE
Repository views not showing the submodules names anymore since 12.0.0

### ISSUE THREAD

**Issue by Skyline124** [gitkraken/vscode-gitlens#1876] opened 2022-03-02 22:09 UTC
# Information

- GitLens Version: `12.0.0`
- Git Version: `git version 2.25.1`
- VSCode Version:
```
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```
- OS Version:
```
$ uname -a
Linux ubuntu 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

# Problem

I noticed that since the last update 12.0.0, in the repository view, we do not see the submodules name in between parentheses next to the name of the parent repository, but only the name of the parent repository. However, hovering above them gives the correct name, see:

![image](https://user-images.githubusercontent.com/14185951/156457018-3455b56a-fd61-4366-8c7a-ff4fda957fa3.png)

I believe this change to be unintentional? In the version 11.7.0 it looked like this, which in my opinion was better:

![image](https://user-images.githubusercontent.com/14185951/156457486-9d8d89d1-6ef5-4369-8320-86e98f7c0fa3.png)

[_red rectangles for confidentiality reasons_]

Steps to Reproduce:

1. Open a repository with submodules in VSCode
2. Enable the repository view in Gitlens
3. See that the submodule names are not displayed but only the parent name directory

Thank you in advance!

I'll be reverting my GitLens to 11.7.0 for now, I am using mostly this repository view when developing :)

**Comment by kchantrell-codan** [comment] 2022-03-03 00:02
I am experiencing the same issue. Upgrading from GitLens 11.7.0 to 12.0.0 causes my submodule names to dissappear in the Repositories view and Commits view. Downgrading to 11.7.0 for now.

I am using 'Remote - SSH' extension (tested with versions v0.74.0 and v0.76.1) to remote into my machine, but not sure if this is relevant.

**Comment by eamodio** [comment] 2022-03-03 07:12
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1854

**Closed by eamodio** 2022-03-03 07:12 UTC
Labels: potential-bug, triage
