### ISSUE TITLE
Since update all repo names just say "repos"

### ISSUE THREAD

**Issue by dustyghost** [gitkraken/vscode-gitlens#1858] opened 2022-03-01 12:14 UTC
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/10135321/156167432-0a0bcf05-3c4c-4cdc-a8de-f7a02e469c75.png)

Extension version: 12.0.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (12.18GB free)|
|Process Argv|--crash-reporter-id 15653d45-c12e-48df-a475-a209fd86adc2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30442553
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343
vscaat:30438848
vsnot107:30443614

```

</details>

**Comment by eamodio** [comment] 2022-03-02 08:19
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1854

**Closed by eamodio** 2022-03-02 08:19 UTC
