### ISSUE TITLE
Branch name used instead of repo name for push

### ISSUE THREAD

**Issue by dancaugherty** [gitkraken/vscode-gitlens#2509] opened 2023-02-16 17:54 UTC
### Description

Whenever I try to push the contents of a local branch to the remote, the name of branch is used for the name of the remote repo. (Branch name redacted below.) I have no idea why, or what to check for.

```
Failed to execute git {
"exitCode": 128,
  "gitErrorCode": "RemoteConnectionError",
  "gitCommand": "push",
  "stdout": "",
  "stderr": "fatal: 'My-branch' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
}
```

### GitLens Version

13.2.0

### VS Code Version

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (1 wk ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

### Git Version

git version 2.38.1

### Logs, Screenshots, Screen Captures, etc

See above. Sorry, that's all I can get.

**Comment by nomad-42** [comment] 2023-02-27 10:19
I've got the same issue - git from a terminal works fine and everything in gitlens looks good except when I try to push and it omits the repo name

**Comment by xiki808** [comment] 2023-04-19 15:19
+1

**Comment by jkelroy** [comment] 2023-04-20 20:33
It looks like this is a duplicate of #2424. I will be closing this and continuing the conversation there.

**Closed by jkelroy** 2023-04-20 20:33 UTC
Labels: bug, triage
