### ISSUE TITLE
Cannot open new files from commit details

### ISSUE THREAD

**Issue by ZeroRin** [gitkraken/vscode-gitlens#2195] opened 2022-09-06 02:39 UTC
### Description

When clicking a newly added file from `COMMITS` side bar, a comparison view is opened with an empty file on the left and the new file on the right.
However, when clicking the same file from `COMMIT Details`, nothing will happen.

### GitLens Version

12.2.1

### VS Code Version

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.17763

### Git Version

git version 2.32.0.windows.2

**Comment by eamodio** [comment] 2022-09-06 03:46
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/2177

**Comment by eamodio** [comment] 2022-09-06 04:09
@ZeroRin Sorry about that -- I completely misread. Will look into it.

**Comment by eamodio** [comment] 2022-09-16 23:19
Fixed by https://github.com/gitkraken/vscode-gitlens/commit/4ce3a8f66b51c1db4030180937a0203eb1aeb920

**Closed by eamodio** 2022-09-16 23:19 UTC
Labels: bug, pending-release
