### ISSUE TITLE
Copy Remote File Url stopped having the line number

### ISSUE THREAD

**Issue by mrkam2** [gitkraken/vscode-gitlens#1633] opened 2021-09-11 01:31 UTC
### Discussed in https://github.com/eamodio/vscode-gitlens/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **mrkam2** August 27, 2021</sup>
Hello,

Why "Copy Remote File Url" is no longer including line numbers in the url (something like `#L15-L17`)? I really miss this feature, is this configurable or is it a bug?

---

Version info:

Version: 1.59.1 (Universal)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

Name: GitLens — Git supercharged
Id: eamodio.gitlens
Description: Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more
Version: 11.6.0
Publisher: Eric Amodio
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens</div>

**Comment by eamodio** [comment] 2021-12-22 07:44
@mrkam2 Can you still reproduce this? It seems to include the line number for me.

**Comment by mrkam2** [comment] 2021-12-22 08:05
When I use it from the document tab context menu, it has no line number.
When I use it from the command palette, it has the line number.

**Comment by eamodio** [comment] 2021-12-22 08:46
Ah, yeah that was an intentional and requested change.

**Comment by eamodio** [comment] 2021-12-31 05:53
I am closing this issue because the current behavior by-design. Thanks!

**Closed by eamodio** 2021-12-31 05:53 UTC
Labels: not-bug
