### ISSUE TITLE
Issue with GitKraken Authentication (local) and GitLens Insiders (WSL)

### ISSUE THREAD

**Issue by j-marcon** [gitkraken/vscode-gitlens#1836] opened 2022-02-25 15:58 UTC
Issue Type: <b>Bug</b>

When I load a project in WSL on Windows 11, I get the following error message:
`Cannot activate the 'GitLens (Insiders)' extension because it depends on the 'GitKraken Authentication' extension, which is not loaded. Would you like to reload the window to load the extension?`

I think the issue comes from the fact that GitLens is running remotely (on WSL Ubuntu) and GitKraken Authentication is running locally because I don't get the issue when I open a local (native Windows) repo.

Extension version: 2022.2.2417
VS Code version: Code - Insiders 1.65.0-insider (8440b8f47231147823ba9696913d642e5f2d9d58, 2022-02-25T05:17:33.544Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.80GB free)|
|Process Argv|--crash-reporter-id 7c898c11-35f8-4504-83b6-6868a96c7096|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|7.70GB (6.85GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc009:30440021
pythonvsnew555:30438690
vsbas813:30436447
vscscmwlcmc:30428972
azactmsal:30432848
vscgsvid1:30433757
dockersurvey3cf:30438169
vscaac:30438845
pynewfile477cf:30443520
vsnot107cf:30443615

```

</details>

**Comment by alkatar21** [comment] 2022-02-28 17:28
The same problem exists in remote containers.

`Cannot activate the 'GitLens — Git supercharged' extension because it depends on the 'GitKraken Authentication' extension, which is not loaded. Would you like to reload the window to load the extension?`

Extension version: v12.0.0
GitKraken Authentication: v1.0.2
VS Code version: 1.64.2

The Problem is, that the new dependency (`GitKraken Authentication`) does prefer the local environment:
`This extension is enabled in the Local Extension Host because it prefers to run there.`

**Comment by highflyer737** [comment] 2022-02-28 17:44
Same here: I'm seeing the same behavior after upgrading to GitLens v12.0.0 with WSL: Ubuntu. Reverting back to v11.7.0 in the remote fixed it with GitKraken Authentication (still) enabled locally.

Extension version: v12.0.0
GitKraken Authentication: v1.0.2
VS Code version: 1.64.2

**Comment by eamodio** [comment] 2022-02-28 17:47
So sorry for the issues. Can you try this version (just remove the `.zip` extension). I think that will fix it.
[gitkraken-authentication-1.0.3.vsix.zip](https://github.com/gitkraken/vscode-gitlens/files/8155508/gitkraken-authentication-1.0.3.vsix.zip)

**Comment by bsaunders23** [comment] 2022-02-28 18:07
Confirming it works in my case as well, thanks for the quick fix!

**Comment by david-redano** [comment] 2022-02-28 18:08
@eamodio are u going to create a new release with the fix shortly?

**Comment by mattwelke** [comment] 2022-02-28 18:08
Ran into this today. Was weird because I'm not using any GitKraken product except this extension (just realized it was made by GitKraken today). I don't want to install an extension related to authenticating with GitKraken. I'm using GitLens as a tool to tell me information about the code like when the line was last modified etc.

**Comment by eamodio** [comment] 2022-02-28 18:08
It should already be out now. I released a new version ~10min ago or so

**Comment by eamodio** [comment] 2022-02-28 18:18
Closing as this should now be resolved.

**Closed by eamodio** 2022-02-28 18:18 UTC
Labels: bug

**Comment by highflyer737** [comment] 2022-02-28 18:25
> > So sorry for the issues. Can you try this version (just remove the `.zip` extension). I think that will fix it. [gitkraken-authentication-1.0.3.vsix.zip](https://github.com/gitkraken/vscode-gitlens/files/8155508/gitkraken-authentication-1.0.3.vsix.zip)
> 
> It works

Works for me too--thanks for the fast fix.

**Comment by Archenoth** [comment] 2022-02-28 18:54
Wowow, always a good feeling to search an issue that was literally fixed half an hour before I searched it up. Nicely done!

**Comment by glebsam** [comment] 2022-02-28 19:30
I had to uninstall both "gitlens" and "gitkraken auth" extensions, reload the window and then install GitLens back. Only that way I've made GitLens work again

**Comment by eamodio** [comment] 2022-02-28 19:55
Argh, sorry folks there was a CI hiccup that I missed. GitKraken Authentication v1.0.3 with the fix will be in the marketplace very shortly (a couple of minutes).

**Comment by j-marcon** [comment] 2022-02-28 20:21
Works for me too. Thanks!

**Comment by kapooramit** [comment] 2022-02-28 20:47
Thank you for the quick fix guys!!
