### ISSUE TITLE
Unable to use GitLens in directories with spaces

### ISSUE THREAD

**Issue by frozenbrain** [gitkraken/vscode-gitlens#2270] opened 2022-10-18 07:21 UTC
### Description

1. Create a new folder with a space in its path (e.g. `C:\Test Repository`)
2. Open it and initialize a Git repository
3. Try to create a new branch using GitLens
4. The command fails with the error message below

This used to work a day or two ago so I assume that this is a regression in the latest update(s).

### GitLens Version

13.0.2

### VS Code Version

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

### Git Version

git version 2.38.0.windows.1

### Logs, Screenshots, Screen Captures, etc

```
> git -C c:/Test Repository branch test master
fatal: cannot change to 'c:/Test': No such file or directory
```

**Comment by eamodio** [comment] 2022-10-18 15:02
Duplicate of #2271

**Closed by eamodio** 2022-10-18 15:02 UTC
Labels: potential-bug, triage
