### ISSUE TITLE
Delete branch doesn't work if repository path contains spaces

### ISSUE THREAD

**Issue by Somnium7** [gitkraken/vscode-gitlens#2277] opened 2022-10-19 15:53 UTC
### Description

1. Checkout repo in any folder, path to which contains spaces.
2. In Source Control tab right click on any branch and delete it.
3. Error (No such file or directory) is shown in terminal (Powershell), because path is unescaped and interpreted incorrectly.

### GitLens Version

13

### VS Code Version

Version: 1.72.2 (system setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

git version 2.34.1.windows.1

**Comment by karthiknadig** [comment] 2022-10-20 00:24
![image](https://user-images.githubusercontent.com/3840081/196828591-5a3691b7-3496-4feb-b619-033c31343a2c.png)

**Comment by eamodio** [comment] 2022-10-20 06:05
Duplicate of #2271

**Closed by eamodio** 2022-10-20 06:05 UTC
Labels: potential-bug, triage
