### ISSUE TITLE
Worktree Create button (+) does not do anything, under certain conditions

### ISSUE THREAD

**Issue by jospvl** [gitkraken/vscode-gitlens#2530] opened 2023-02-28 08:47 UTC
### Description

When there are two or more worktrees and the active worktree is not Main, the + button does not do anything.
It does work when the Main worktree is active, though.

This is probably related to issue #2301 but still occurring in v13.3.1 and in pre-release v2023.2.2411.

When it doesn't work, GitLens debugging output pane reports:
Vc.execute — failed
TypeError: Cannot read properties of undefined (reading 'path')

### GitLens Version

13.3.1

### VS Code Version

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

### Git Version

git version 2.39.2

**Comment by d13** [comment] 2023-03-01 15:38
Unfortunately, I'm not able to reproduce this.

Can you please enable debug logging by running the _GitLens: Enable Debug Logging_ command from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ & _GitLens (Git)_ channels in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the logs from the _GitLens_ channel, and if its Git related please also attach the logs from the _GitLens (Git)_ channel.

Thank you!

**Comment by sedghi** [comment] 2023-03-01 18:58
happening again for me. I reported it before [here](https://github.com/gitkraken/vscode-gitlens/issues/2301) and it was fixed

**Comment by sedghi** [comment] 2023-03-01 20:10
I use a clone --bare for my repo locally, so I have the following tree (I hope that helps) - I've been using gitlens worktree from the time you added it to the plus, and it was working fine 

![image](https://user-images.githubusercontent.com/7490180/222254397-4db059b3-f8a7-42a6-b2fa-5b46adcdb514.png)

**Comment by axosoft-ramint** [comment] 2023-03-03 21:54
@sedghi Can you check if your `gitlens.detectNestedRepositories` setting is on?

![image](https://user-images.githubusercontent.com/67011668/222836703-c7160da3-98d3-4bc3-aba1-17fcf42e3311.png)

If it is, can you temporarily turn it off and check if it fixes the issue?

**Comment by sedghi** [comment] 2023-03-05 02:22
it is not on for me

**Comment by nekocom3745** [comment] 2023-03-05 14:57
gitlens.detectNestedRepositoriesje

**Comment by sedghi** [comment] 2023-03-06 14:07
I just noticed the `Delete worktree` doesn't work anymore too

**Comment by eamodio** [comment] 2023-03-07 05:31
@sedghi Can you see if the latest version (either stable or pre-release) fixes the issue for you?

**Comment by sedghi** [comment] 2023-03-07 14:46
No unfortunatellly, 

clicking + results in 

```
[2023-03-07 14:45:30.561] [  992] ViewCommands.createWorktree
[2023-03-07 14:45:30.569] [  997] W(/Users/alireza/dev/cornerstone3D-beta.git/feat/remaining-rtss).getMainRepository
[2023-03-07 14:45:30.572] [  998] GitProviderService.getOrOpenRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git), t={"detectNested":false,"force":true,"closeOnOpen":true})
[2023-03-07 14:45:30.572] [  999] GitProviderService.getRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git))
[2023-03-07 14:45:30.572] [  999] GitProviderService.getRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git)) returned undefined • 0 ms
[2023-03-07 14:45:30.573] [  998] GitProviderService.getOrOpenRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git), t={"detectNested":false,"force":true,"closeOnOpen":true}) returned undefined • 0 ms
[2023-03-07 14:45:30.573] [  997] W(/Users/alireza/dev/cornerstone3D-beta.git/feat/remaining-rtss).getMainRepository returned undefined • 3 ms
[2023-03-07 14:45:30.573] [  993] sh.execute — failed
Error: Missing repository
```

right clicking and delete

```
[2023-03-07 14:46:04.945] [  99b] ViewCommands.deleteWorktree(e=Zo(gitlens:repository(/Users/alireza/dev/cornerstone3D-beta.git/feat/remaining-rtss):worktree(/Users/alireza/dev/cornerstone3D-beta.git/feat/events-improv)), undefined)
[2023-03-07 14:46:04.949] [  9a0] W(/Users/alireza/dev/cornerstone3D-beta.git/feat/remaining-rtss).getMainRepository
[2023-03-07 14:46:04.950] [  9a1] GitProviderService.getOrOpenRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git), t={"detectNested":false,"force":true,"closeOnOpen":true})
[2023-03-07 14:46:04.950] [  9a2] GitProviderService.getRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git))
[2023-03-07 14:46:04.950] [  9a2] GitProviderService.getRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git)) returned undefined • 0 ms
[2023-03-07 14:46:04.951] [  9a1] GitProviderService.getOrOpenRepository(e=Uri(file:///Users/alireza/dev/cornerstone3D-beta.git), t={"detectNested":false,"force":true,"closeOnOpen":true}) returned undefined • 0 ms
[2023-03-07 14:46:04.951] [  9a0] W(/Users/alireza/dev/cornerstone3D-beta.git/feat/remaining-rtss).getMainRepository returned undefined • 1 ms
[2023-03-07 14:46:04.951] [  99c] sh.execute — failed
Error: Missing repository
````

**Comment by axosoft-ramint** [comment] 2023-03-08 16:43
@sedghi Thanks for the info! Could you try the latest pre-release version (`v2023.3.804` or later) of GitLens once more? We pushed an update to the pre-release since your last post that may have addressed this issue.

**Comment by sedghi** [comment] 2023-03-08 17:02
It worked!

**Comment by axosoft-ramint** [comment] 2023-03-08 17:06
Fixed in commit: https://github.com/gitkraken/vscode-gitlens/commit/d8993ee3351e032549a8058f8b8eb1a9ebfd65a9

**Closed by axosoft-ramint** 2023-03-08 17:06 UTC
Labels: bug, pending-release, verified ✔, area-worktrees
